DROP TABLE IF EXISTS evidence_embeddings CASCADE;
DROP TABLE IF EXISTS artifact_finalize_outbox CASCADE;
DROP TABLE IF EXISTS broker_outbox CASCADE;
DROP TABLE IF EXISTS measurement_job_queries CASCADE;
DROP TABLE IF EXISTS measurement_job_specs CASCADE;
DROP TABLE IF EXISTS verification_job_specs CASCADE;
DROP TABLE IF EXISTS generation_job_specs CASCADE;
DROP TABLE IF EXISTS evidence_pack_job_specs CASCADE;
DROP TABLE IF EXISTS collection_job_queries CASCADE;
DROP TABLE IF EXISTS collection_job_specs CASCADE;
DROP TABLE IF EXISTS durable_jobs CASCADE;
DROP TABLE IF EXISTS placement_measurements CASCADE;
DROP TABLE IF EXISTS publication_submissions CASCADE;
DROP TABLE IF EXISTS publication_requests CASCADE;
DROP TABLE IF EXISTS placement_reviews CASCADE;
DROP TABLE IF EXISTS placement_claim_evidence CASCADE;
DROP TABLE IF EXISTS placement_claims CASCADE;
DROP TABLE IF EXISTS placement_package_versions CASCADE;
DROP TABLE IF EXISTS placement_packages CASCADE;
DROP TABLE IF EXISTS prompt_bundles CASCADE;
DROP TABLE IF EXISTS generation_template_releases CASCADE;
DROP TABLE IF EXISTS prompt_skill_versions CASCADE;
DROP TABLE IF EXISTS prompt_skills CASCADE;
DROP TABLE IF EXISTS evidence_pack_items CASCADE;
DROP TABLE IF EXISTS evidence_pack_attempts CASCADE;
DROP TABLE IF EXISTS placement_brief_subject_entities CASCADE;
DROP TABLE IF EXISTS placement_brief_versions CASCADE;
DROP TABLE IF EXISTS placement_briefs CASCADE;
DROP TABLE IF EXISTS placement_opportunities CASCADE;
DROP TABLE IF EXISTS publication_destinations CASCADE;
DROP TABLE IF EXISTS campaign_monitoring_queries CASCADE;
DROP TABLE IF EXISTS campaign_entities CASCADE;
DROP TABLE IF EXISTS geo_campaigns CASCADE;
DROP TABLE IF EXISTS evidence_items CASCADE;
DROP TABLE IF EXISTS monitoring_queries CASCADE;
DROP TABLE IF EXISTS market_profiles CASCADE;
DROP TABLE IF EXISTS product_entities CASCADE;
DROP TABLE IF EXISTS project_memberships CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS identities CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP FUNCTION IF EXISTS geo_assert_publication_package_approved();
DROP FUNCTION IF EXISTS geo_assert_domain_job_kind();
DROP FUNCTION IF EXISTS geo_assert_package_version_approval();
DROP FUNCTION IF EXISTS geo_protect_evidence_pack_attempt();
DROP FUNCTION IF EXISTS geo_protect_package_version_content();
DROP FUNCTION IF EXISTS geo_reject_immutable_change();
DROP FUNCTION IF EXISTS geo_current_project_id();
