DROP TRIGGER workflow_c_provider_sampling_durable_status ON durable_jobs;
REVOKE ALL ON FUNCTION geo_reconcile_workflow_c_provider_sampling_durable_status()
FROM PUBLIC, geo_app, geo_worker, geo_readonly;
DROP FUNCTION geo_reconcile_workflow_c_provider_sampling_durable_status();
