DROP TABLE attribution_snapshots;
DROP TRIGGER attribution_revenues_immutable ON attribution_revenues;
DROP TABLE attribution_revenues;
DROP TRIGGER attribution_deals_immutable ON attribution_deals;
DROP TABLE attribution_deals;
DROP TRIGGER attribution_conversions_immutable ON attribution_conversions;
DROP TABLE attribution_conversions;
DROP TRIGGER attribution_stages_immutable ON attribution_stages;
DROP TABLE attribution_stages;
DROP TRIGGER attribution_leads_immutable ON attribution_leads;
DROP TABLE attribution_leads;
DROP TABLE attribution_imports;
DROP TRIGGER attribution_exposures_immutable ON attribution_exposures;
DROP TABLE attribution_exposures;
DROP TRIGGER attribution_touches_immutable ON attribution_touches;
DROP TABLE attribution_touches;
DROP TABLE attribution_sessions;
DROP TRIGGER attribution_trace_links_immutable ON attribution_trace_links;
DROP TABLE attribution_trace_links;
DROP TABLE attribution_collectors;
DROP TABLE attribution_policies;
DROP FUNCTION geo_attribution_immutable();
