from __future__ import annotations

from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class AdminCustomerWebContractsTest(unittest.TestCase):
    def test_admin_projects_status_filter_does_not_expose_configured_history(self) -> None:
        page_source = (ROOT / "apps/admin-web/app/projects/page.tsx").read_text(encoding="utf-8")

        self.assertIn("<option value=\"active\">运行中</option>", page_source)
        self.assertIn("<option value=\"paused\">暂停中</option>", page_source)
        self.assertNotIn("暂停中（历史已配置）", page_source)
        self.assertNotIn("<option value=\"configured\"", page_source)

    def test_admin_new_project_uses_server_action_and_no_inert_buttons(self) -> None:
        form_source = (ROOT / "apps/admin-web/app/projects/new/CreateProjectForm.tsx").read_text(encoding="utf-8")
        action_source = (ROOT / "apps/admin-web/app/projects/new/actions.ts").read_text(encoding="utf-8")
        page_source = (ROOT / "apps/admin-web/app/projects/new/page.tsx").read_text(encoding="utf-8")

        self.assertIn("useActionState(createProjectAction", form_source)
        self.assertIn("POST", action_source)
        self.assertIn('runtimeRequest<RuntimeProjectCreateResponse>("/v1/projects/runtime"', action_source)
        self.assertIn("customerInvitationUrl", action_source)
        self.assertNotIn("parseJsonObject", action_source)
        self.assertIn("3 到 5 个", form_source)
        self.assertIn("role=\"dialog\"", form_source)
        self.assertIn("提交前确认", form_source)
        self.assertIn("返回修改", form_source)
        self.assertIn("确认创建项目", form_source)
        self.assertIn("邀请 token 只显示一次", form_source)
        self.assertIn("打开项目详情", form_source)
        self.assertIn("打开客户邀请入口", form_source)
        self.assertIn("onClick={handleEdit}", form_source)
        self.assertIn("onClick={handleConfirmSubmit}", form_source)
        self.assertIn("<option value=\"api\">真实 API</option>", form_source)
        self.assertIn("<option value=\"manual\">手工补录</option>", form_source)
        self.assertIn('collectionMode: "api"', form_source)
        self.assertIn('requiredString(formData, "collection_mode", "api")', action_source)
        self.assertIn('market_code: requiredString(formData, "market_code", "GLOBAL")', action_source)
        self.assertIn('timezone = requiredString(formData, "timezone", "UTC")', action_source)
        self.assertIn('currency: requiredString(formData, "currency", "USD")', action_source)
        self.assertIn('score_formula_version: "visibility_v1.0"', action_source)
        self.assertIn("市场与行业", form_source)
        self.assertIn("初始状态：暂停中", form_source)
        self.assertNotIn('name="launch_status"', form_source)
        self.assertNotIn('name="schedule"', form_source)
        self.assertNotIn('name="external_connectors"', form_source)
        self.assertNotIn("<option value=\"fixture\"", form_source)
        self.assertNotIn("AU GEO Pilot", form_source)
        self.assertNotIn("ExampleBrand", form_source)
        self.assertNotIn('method="get"', page_source)
        self.assertNotIn("后续会改成", page_source)

    def test_admin_project_detail_wires_customer_access_runtime_actions(self) -> None:
        page_source = (ROOT / "apps/admin-web/app/projects/[project_id]/page.tsx").read_text(encoding="utf-8")
        action_source = (ROOT / "apps/admin-web/app/projects/[project_id]/actions.ts").read_text(encoding="utf-8")
        component_source = (ROOT / "apps/admin-web/app/projects/[project_id]/ProjectActions.tsx").read_text(encoding="utf-8")
        compose_source = (ROOT / "infra/docker-compose.yml").read_text(encoding="utf-8")

        self.assertIn("/v1/projects/runtime/action", action_source)
        self.assertIn("/v1/project-launch-configs/runtime", action_source)
        self.assertIn("/v1/project-entities/runtime/brand", action_source)
        self.assertIn("/v1/project-entities/runtime/competitors", action_source)
        self.assertIn("/v1/collection-runs/runtime/fixture", action_source)
        self.assertIn('"/v1/prompts/runtime"', action_source)
        self.assertIn("/v1/prompts/runtime/import.csv", action_source)
        self.assertIn("/v1/knowledge/pipeline-runs/runtime", action_source)
        self.assertIn("/v1/knowledge/import-jobs/runtime", action_source)
        self.assertIn("/v1/project-member-invitations/runtime", action_source)
        self.assertNotIn("/v1/customer-portal/tokens/runtime", action_source)
        self.assertNotIn("/v1/customer-portal/tokens/runtime/revoke", action_source)
        self.assertIn("/v1/project-member-invitations/runtime/action", action_source)
        self.assertIn("redirect(`/projects/${pid}?tab=prompts&prompt_tab=config", action_source)
        self.assertIn("revalidateProject", action_source)
        self.assertIn("customerInvitationUrl", action_source)
        self.assertIn("NEXT_PUBLIC_CUSTOMER_WEB_BASE_URL", compose_source)
        self.assertNotIn("/v1/customer-portal/tokens/runtime", page_source)
        self.assertIn("/v1/score-weight-configs/runtime", page_source)
        self.assertIn("/v1/score-formulas/runtime", page_source)
        self.assertIn("/v1/score-weight-profiles/runtime", page_source)
        self.assertIn("InvitationForm", page_source)
        self.assertIn("InvitationList", page_source)
        self.assertNotIn("TokenList", page_source)
        self.assertIn("MemberList", page_source)
        self.assertNotIn("TokenCreateForm", page_source)
        self.assertNotIn("TokenRevokeForm", page_source)
        self.assertIn("ProjectBasicsForm", page_source)
        self.assertIn("LaunchConfigForm", page_source)
        self.assertNotIn("BrandEntityForm", page_source)
        self.assertIn("CompetitorEditor", page_source)
        self.assertIn("FixtureE2EForm", page_source)
        self.assertIn("adminDevToolsEnabled", page_source)
        self.assertIn("devToolsEnabled ?", page_source)
        self.assertIn("生产环境不暴露本地测试入口", page_source)
        self.assertIn("PromptEditor", page_source)
        self.assertIn("PromptImportForm", page_source)
        self.assertIn("KnowledgePanel", page_source)
        self.assertIn("PromptGenerationPanel", page_source)
        self.assertIn("PromptCandidatePanel", page_source)
        self.assertIn("PromptTemplatePanel", page_source)
        self.assertIn("KnowledgeDocumentImportPanel", page_source)
        self.assertIn("KnowledgeDashboardPanel", page_source)
        self.assertIn("KnowledgeQualityPanel", page_source)
        self.assertIn("KnowledgeQualityRiskAcceptForm", page_source)
        self.assertIn("acceptKnowledgeQualityRiskAction", component_source)
        self.assertIn("/v1/knowledge/quality-gate-runs/runtime/", action_source)
        self.assertIn("/accept-risk", action_source)
        self.assertIn("security_gate", component_source)
        self.assertIn("traceability_gate", component_source)
        self.assertNotIn("KnowledgeFactImportForm", page_source)
        self.assertIn("/v1/knowledge/chunks/runtime/search", page_source)
        self.assertIn("/v1/knowledge/parser-runs/runtime", page_source)
        self.assertIn("/v1/knowledge/page-snapshots/runtime", page_source)
        self.assertNotIn("/v1/knowledge-facts/runtime/search", page_source)
        self.assertIn("?tab=knowledge&knowledge_tab=processing", action_source)
        self.assertIn("知识库检索", page_source)
        self.assertIn("创建完整知识库 Pipeline", component_source)
        self.assertIn("Chunk + BGE-M3", component_source)
        self.assertIn('name="source_files"', component_source)
        self.assertIn("knowledgeFileQueue", component_source)
        self.assertIn("查看证据链", component_source)
        self.assertIn("edited_text", component_source)
        self.assertIn("merged_into_fact_id", component_source)
        self.assertIn("model_config", component_source)
        self.assertIn("evaluation_set", component_source)
        self.assertIn("OperationsPanel", page_source)
        self.assertIn("运营工作台", page_source)
        self.assertNotIn("ConnectorSecretPanel", page_source)
        self.assertIn("ManualBackfillPanel", page_source)
        self.assertIn("HumanReviewPanel", page_source)
        self.assertIn("ReportCenterPanel", page_source)
        self.assertIn("ActionPlanPanel", page_source)
        self.assertIn("BrandAssetsPanel", page_source)
        self.assertIn("QualityOpsPanel", page_source)
        self.assertIn("/v1/connectors/runtime/secrets", action_source)
        self.assertIn("/v1/connectors/runtime/test", action_source)
        self.assertIn("/v1/evidence-runs/runtime/manual-backfill", action_source)
        self.assertIn("/v1/human-reviews/runtime", action_source)
        self.assertIn("/management-events", action_source)
        self.assertIn("/v1/report-export-jobs/runtime", action_source)
        self.assertIn("/v1/action-plans/runtime/", action_source)
        self.assertIn("/v1/knowledge/content-drafts/runtime/", action_source)
        self.assertIn("/v1/manual-distribution-records/runtime/", action_source)
        self.assertIn("ContentDraftReviewForm", component_source)
        self.assertIn("ManualDistributionBackfillForm", component_source)
        self.assertIn("保存内容审核", component_source)
        self.assertIn("保存回填", component_source)
        self.assertNotIn("后端尚未提供内容审核/Distribution URL 回填 mutation", component_source)
        self.assertIn("mainTabs", page_source)
        self.assertIn("basicTabs", page_source)
        self.assertIn("statusTabs", page_source)
        self.assertIn("Prompt", page_source)
        self.assertIn("promptTabs", page_source)
        self.assertIn("knowledgeTabs", page_source)
        self.assertIn("tab: \"prompts\"", page_source)
        self.assertIn("Prompt 总数", page_source)
        self.assertIn("每页显示", page_source)
        self.assertIn("prompt_limit", page_source)
        self.assertIn("prompt_tab", page_source)
        self.assertIn("knowledge_tab", page_source)
        self.assertIn("导出 CSV", page_source)
        self.assertIn("项目看板", page_source)
        self.assertIn("/v1/collection-runs/runtime", page_source)
        self.assertNotIn("ConnectorSecretPanel", component_source)
        self.assertNotIn("ConnectorSecretForm", component_source)
        self.assertIn("rows.map(([label, value], index)", page_source)
        self.assertIn('key={`${index}-${label}-${value}`}', page_source)
        self.assertNotIn('key={`${label}-${value}`}', page_source)
        self.assertNotIn("createPortalTokenAction", component_source)
        self.assertIn("useActionState(saveProjectAndBrandAction", component_source)
        self.assertIn("useActionState(saveLaunchConfigAction", component_source)
        self.assertIn("useActionState(saveScoreWeightProfileAction", component_source)
        self.assertIn("useActionState(saveCompetitorEntityAction", component_source)
        self.assertIn("useActionState(savePromptAction", component_source)
        self.assertIn("useActionState(runFixtureE2EAction", component_source)
        self.assertIn("<option value=\"api\">真实 API</option>", component_source)
        self.assertIn("<option value=\"manual\">手工补录</option>", component_source)
        self.assertNotIn("<option value=\"fixture\"", component_source)
        self.assertNotIn("<option value=\"fixture_only\"", component_source)
        self.assertIn("competitor_domains_snapshot", component_source)
        self.assertIn("accordionItem", component_source)
        self.assertIn("ConnectorConfigCard", component_source)
        self.assertIn("显示已保存 API key", component_source)
        self.assertIn("type=\"text\"", component_source)
        self.assertIn("connectorModelOptions(provider, mode)", component_source)
        self.assertIn("另存为自定义评分方案", component_source)
        self.assertIn("权重保存时会自动归一化为两位小数", component_source)
        self.assertIn("score_weight_profile", page_source)
        self.assertNotIn("配置文件 / 记录", component_source)
        self.assertIn("ScoreWeightEditor", component_source)
        self.assertIn("AI 回答是否明确提到目标品牌", component_source)
        self.assertNotIn("来自评分公式配置的权重项。", component_source)
        self.assertIn("OpenAI 连接器", component_source)
        self.assertIn("Perplexity 连接器", component_source)
        self.assertIn("Google AI Mode", component_source)
        self.assertIn("运行模式", component_source)
        self.assertIn("模型 / 服务", component_source)
        self.assertIn("测试连接", component_source)
        self.assertIn("deepseek-v4-flash", component_source)
        self.assertIn('input {...hydrationControlProps} type="hidden" name="provider"', component_source)
        self.assertNotIn('name="provider"\\n        value={provider}\\n        formAction={testAction}', component_source)
        self.assertIn("ProjectStatusControls", page_source)
        self.assertIn("启动条件未满足", component_source)
        self.assertIn("setDraftCount", component_source)
        self.assertIn("新增竞品", component_source)
        self.assertIn("修改", component_source)
        self.assertIn("撤销邀请", component_source)
        self.assertIn("replace_existing_pending", component_source)
        self.assertIn("existing_pending_invitation_ids", component_source)
        self.assertIn("旧 invitation token 将无法再使用", component_source)
        self.assertIn("确认让旧邀请失效并生成新的邀请", component_source)
        self.assertIn("当前可用邀请", component_source)
        self.assertIn("历史 / 已失效邀请", component_source)
        self.assertIn('<details className="historyPanel" open>', component_source)
        self.assertIn("inactiveInvitationList", component_source)
        self.assertIn('status: "pending"', action_source)
        self.assertIn("admin_web_customer_invitation_replace_existing_pending", action_source)
        self.assertIn("旧邀请已失效，新的邀请已创建", action_source)
        self.assertIn("请确认旧邀请 token 失效后再生成新的邀请", action_source)
        self.assertIn("无法检查已有待处理邀请，未生成新的邀请", action_source)
        self.assertIn("pendingInvitations={invitations.records.filter", page_source)
        self.assertIn("邀请、成员与安全会话", page_source)
        self.assertIn("URL 不携带长期 token", page_source)
        self.assertNotIn("门户 token / session", page_source)
        self.assertIn("Prompt 文本", component_source)
        self.assertIn("调度频率", component_source)
        self.assertIn("项目与品牌", page_source)
        self.assertIn("OperationSection", page_source)
        self.assertIn("Google 补录", page_source)
        self.assertIn("人工复核", page_source)
        self.assertIn("报告中心", page_source)
        self.assertIn("行动与复测", page_source)
        self.assertIn("生成提问 Prompt 候选", component_source)
        self.assertIn("prompt_template_id", component_source)
        self.assertIn("knowledge_source_policy", component_source)
        self.assertIn("仅已批准知识", component_source)
        self.assertIn("所有来源统一进入生产 Pipeline", component_source)
        self.assertIn("MinerU", component_source)
        self.assertIn("Docling", component_source)
        self.assertIn("知识库质检", component_source)
        self.assertIn("内容与分发", page_source)
        self.assertIn("品牌资产", page_source)
        self.assertIn("质量与运维", page_source)
        self.assertNotIn("<summary><span>新增竞品</span>", component_source)
        self.assertNotIn("高级 JSON 配置", page_source)
        self.assertNotIn("当前页样本", page_source)
        self.assertNotIn("<pre>{JSON.stringify(record", page_source)
        self.assertNotIn("<pre>{JSON.stringify(launchConfig", page_source)

    def test_admin_projects_list_supports_filters_and_archive_restore(self) -> None:
        page_source = (ROOT / "apps/admin-web/app/projects/page.tsx").read_text(encoding="utf-8")
        component_source = (ROOT / "apps/admin-web/app/projects/[project_id]/ProjectActions.tsx").read_text(encoding="utf-8")

        self.assertIn("status", page_source)
        self.assertIn("include_archived", page_source)
        self.assertIn("搜索项目", page_source)
        self.assertIn("ProjectLifecycleForm", page_source)
        self.assertIn("归档项目", component_source)
        self.assertIn("恢复为暂停中", component_source)
        self.assertIn("window.confirm", component_source)

    def test_development_board_reads_latest_production_v1_checklist(self) -> None:
        page_source = (ROOT / "apps/admin-web/app/development-board/page.tsx").read_text(encoding="utf-8")
        css_source = (ROOT / "apps/admin-web/app/globals.css").read_text(encoding="utf-8")
        compose_source = (ROOT / "infra/docker-compose.yml").read_text(encoding="utf-8")
        dockerfile_source = (ROOT / "apps/admin-web/Dockerfile").read_text(encoding="utf-8")

        self.assertIn('export const dynamic = "force-dynamic"', page_source)
        self.assertIn("GEO-Production-v1执行进度-checklist-2026-07-05.md", page_source)
        self.assertIn("GEO-当前项目进度汇报-2026-07-10.md", page_source)
        self.assertIn("tmp/frontend-knowledge-lifecycle-smoke/latest.json", page_source)
        self.assertIn("readFile(checklistPath", page_source)
        self.assertIn("parseChecklist", page_source)
        self.assertIn("GEO Production v1 执行看板", page_source)
        self.assertIn("Checklist 生成日期", page_source)
        self.assertIn("文件最后更新时间", page_source)
        self.assertIn("总体完成率", page_source)
        self.assertIn("Production Ready", page_source)
        self.assertIn("待补正式证据", page_source)
        self.assertIn("commit: string", page_source)
        self.assertIn("productionReady: boolean", page_source)
        self.assertIn("productionBlockersFor", page_source)
        self.assertNotIn("commit hash 未填写", page_source)
        self.assertIn("checklist.totals.productionReady", page_source)
        self.assertIn("后续升级边界", page_source)
        self.assertIn("statusPill-done", css_source)
        self.assertIn("statusPill-production", css_source)
        self.assertIn("developmentBlockers", css_source)
        self.assertIn("developmentHeroGrid", css_source)
        self.assertIn("../docs:/app/docs:ro", compose_source)
        self.assertIn("COPY docs ./docs", dockerfile_source)
        self.assertNotIn("const items = [", page_source)
        self.assertNotIn("工程拆分与上线前检查", page_source)

    def test_runtime_project_e2e_verifier_targets_existing_project(self) -> None:
        script_source = (ROOT / "scripts/verify_runtime_project_e2e.py").read_text(encoding="utf-8")

        self.assertIn("--project-id", script_source)
        self.assertIn("workers/collector_worker/run_collection_slice.py", script_source)
        self.assertIn("--persist-analysis", script_source)
        self.assertIn("answer_runs", script_source)
        self.assertIn("visibility_score_snapshots", script_source)
        self.assertIn("report_exports", script_source)
        self.assertIn("traceability_bundles", script_source)

    def test_customer_web_uses_runtime_data_instead_of_placeholder_score(self) -> None:
        home_source = (ROOT / "apps/customer-web/app/page.tsx").read_text(encoding="utf-8")
        runtime_source = (ROOT / "apps/customer-web/app/runtime.ts").read_text(encoding="utf-8")
        module_source = (ROOT / "apps/customer-web/app/portal/[module]/page.tsx").read_text(encoding="utf-8")
        artifact_route_source = (ROOT / "apps/customer-web/app/api/report-artifact/route.ts").read_text(encoding="utf-8")

        self.assertIn("invitation_id", home_source)
        self.assertIn("invite_token", home_source)
        self.assertIn("bundle?.access?.member_user_id", home_source)
        self.assertIn("actorId?: string", runtime_source)
        self.assertIn("latestScore(runtime.scores)", home_source)
        self.assertNotIn("const score = undefined", home_source)
        self.assertNotIn('"36%"', home_source)
        for endpoint in (
            "/v1/visibility-scores/runtime",
            "/v1/evidence-runs/runtime",
            "/v1/collection-runs/runtime",
            "/v1/citation-graphs/runtime",
            "/v1/reports/runtime",
            "/v1/report-export-jobs/runtime",
            "/v1/action-plans/runtime",
            "/v1/traceability/runtime",
        ):
            self.assertIn(endpoint, runtime_source)
        self.assertIn("/api/report-artifact", module_source)
        self.assertIn("function KeyValueGrid", module_source)
        self.assertIn("function RecordList", module_source)
        self.assertIn("正式交付包准备状态", module_source)
        self.assertIn("Traceability Bundle", module_source)
        self.assertIn("行动建议", module_source)
        self.assertNotIn("JSON.stringify", module_source)
        self.assertNotIn("<pre>", module_source)
        self.assertIn("/v1/reports/runtime/", artifact_route_source)
        self.assertIn("X-GEO-Session-Token", artifact_route_source)
        self.assertNotIn("/v1/customer-portal/access", artifact_route_source)
        self.assertNotIn("X-GEO-Actor-Id", artifact_route_source)
        self.assertNotIn("portal_token", home_source)
        self.assertNotIn("portal_token", module_source)
        self.assertNotIn("接入后会在此页", module_source)


if __name__ == "__main__":
    unittest.main()
