from __future__ import annotations

from pathlib import Path
import unittest


class WebConsoleContractsTest(unittest.TestCase):
    def test_runtime_console_contains_traceability_links_and_graph_maps(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("function CitationGraphMap", page_source)
        self.assertIn("function TraceabilityMap", page_source)
        self.assertIn("function NodeLink", page_source)
        self.assertIn('id={anchorId("traceability-map", "runtime")}', page_source)
        self.assertIn('id={anchorId("source-node", item.node.id)}', page_source)
        self.assertIn('id={anchorId("answer-run", run.answer_run.id)}', page_source)
        self.assertIn('href={anchorHref("answer-run", run.answer_run.id)}', page_source)
        self.assertIn('href={anchorHref("source-node", item.node.id)}', page_source)

    def test_runtime_console_styles_highlight_deep_link_targets(self) -> None:
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn(".graphCanvas", css_source)
        self.assertIn(".traceMapCanvas", css_source)
        self.assertIn(".nodeLink", css_source)
        self.assertIn(":target", css_source)

    def test_runtime_console_discloses_report_method_boundaries(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Method Disclosure", page_source)
        self.assertIn("Google coverage", page_source)
        self.assertIn("Google gate", page_source)
        self.assertIn("API/browser fidelity", page_source)
        self.assertIn("Trigger denominator", page_source)
        self.assertIn("Mention denominator", page_source)
        self.assertIn("Recommendation denominator", page_source)
        self.assertIn("Attempted records", page_source)
        self.assertIn("Surface-triggered records", page_source)
        self.assertIn("Evidence trigger rate", page_source)
        self.assertIn("score_rate_denominators", page_source)
        self.assertIn("Access distribution", page_source)
        self.assertIn("Google remains outside the main scoring denominator", page_source)

    def test_runtime_console_surfaces_api_browser_fidelity_checks(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn('fidelityChecks: "/v1/fidelity-checks/runtime"', page_source)
        self.assertIn('fidelityTrend: "/v1/fidelity-checks/runtime/trend"', page_source)
        self.assertIn("RuntimeFidelityCheck", page_source)
        self.assertIn("RuntimeFidelityTrend", page_source)
        self.assertIn("api_browser_fidelity_checked", page_source)
        self.assertIn("Fidelity audit", page_source)
        self.assertIn("Fidelity query", page_source)
        self.assertIn("Fidelity trend", page_source)
        self.assertIn("Trend query", page_source)
        self.assertIn("Payload hash", page_source)

    def test_runtime_console_surfaces_au_launch_status_gate(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn('launchStatus: "/v1/launch-status/au"', page_source)
        self.assertIn("type AuLaunchStatus", page_source)
        self.assertIn("AU Launch Gate", page_source)
        self.assertIn("ready_for_customer_report_handoff", page_source)
        self.assertIn("launch_status_hash", page_source)
        self.assertIn("p0a_design_partner", page_source)
        self.assertIn("p0b_google", page_source)
        self.assertIn("p0c_customer_report", page_source)
        self.assertIn("Remaining blockers", page_source)
        self.assertIn("Next action", page_source)
        self.assertIn("paths.launchStatus", page_source)
        self.assertIn(".launchStatusPanel", css_source)
        self.assertIn(".launchStatusHeader", css_source)
        self.assertIn(".launchStageGrid", css_source)
        self.assertIn(".launchEvidenceGrid", css_source)
        self.assertIn(".launchBlockers", css_source)

    def test_runtime_console_surfaces_collection_run_quality(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn('collectionRuns: "/v1/collection-runs/runtime"', page_source)
        self.assertIn("type CollectionRun", page_source)
        self.assertIn("Collection Run Quality", page_source)
        self.assertIn("Success rate", page_source)
        self.assertIn("Trigger rate", page_source)
        self.assertIn("Answer rate", page_source)
        self.assertIn("Total cost", page_source)
        self.assertIn("Avg cost/run", page_source)
        self.assertIn("Avg duration", page_source)
        self.assertIn("Duration", page_source)
        self.assertIn("duration_ms", page_source)
        self.assertIn("total_duration_ms", page_source)
        self.assertIn("average_duration_ms", page_source)
        self.assertIn("failure_summary", page_source)

    def test_runtime_console_surfaces_parser_comparison(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Parser agreement", page_source)
        self.assertIn("parser_comparison", page_source)
        self.assertIn("parser_ab_compare_v1", page_source)
        self.assertIn("parserComparisonText", page_source)
        self.assertIn("mismatches", page_source)
        self.assertIn("llm_call_log", page_source)
        self.assertIn("LLM call", page_source)

    def test_runtime_console_surfaces_score_weight_configuration(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Score Weights", page_source)
        self.assertIn("saveScoreWeightConfig", page_source)
        self.assertIn("/v1/score-weight-configs/runtime", page_source)
        self.assertIn("/v1/score-formulas/runtime", page_source)
        self.assertIn("Formula catalog", page_source)
        self.assertIn("Formula version", page_source)
        self.assertIn("Selected formula", page_source)
        self.assertIn("Formula status", page_source)
        self.assertIn("Formula note", page_source)
        self.assertIn("Supersedes", page_source)
        self.assertIn("component_weights_snapshot", page_source)
        self.assertIn("Weight snapshot", page_source)

    def test_runtime_console_surfaces_brand_logo_upload(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Logo Upload", page_source)
        self.assertIn("uploadProjectBrandLogo", page_source)
        self.assertIn("/v1/project-brand-kits/runtime/logo", page_source)
        self.assertIn('name="brand_logo"', page_source)
        self.assertIn('type="file"', page_source)
        self.assertIn("project_brand_logo_uploaded", page_source)
        self.assertIn("Theme Editor", page_source)
        self.assertIn("themeEditorPreview", page_source)
        self.assertIn("advanced white-label theme editor", page_source)
        self.assertIn("Template payload", page_source)
        self.assertIn('type="color"', page_source)
        self.assertIn("primary_color", page_source)
        self.assertIn("secondary_color", page_source)
        self.assertIn("project_brand_kit_saved", page_source)
        self.assertIn("Brand Assets", page_source)
        self.assertIn("RuntimeProjectBrandAssetVersion", page_source)
        self.assertIn("RuntimeProjectBrandAsset", page_source)
        self.assertIn("activateProjectBrandAssetVersion", page_source)
        self.assertIn("saveProjectBrandAsset", page_source)
        self.assertIn("updateProjectBrandAssetScanStatus", page_source)
        self.assertIn("/v1/project-brand-kits/runtime/assets", page_source)
        self.assertIn("/v1/project-brand-kits/runtime/assets/activate", page_source)
        self.assertIn("/v1/project-brand-assets/runtime", page_source)
        self.assertIn("/v1/project-brand-assets/runtime/${assetId}/scan-status", page_source)
        self.assertIn('name="asset_url"', page_source)
        self.assertIn('name="preview_url"', page_source)
        self.assertIn('name="scan_status"', page_source)
        self.assertIn("project_brand_asset_scan_recorded", page_source)
        self.assertIn("Asset Register", page_source)
        self.assertIn("Asset Library", page_source)
        self.assertIn("project_brand_asset_library_v1", page_source)
        self.assertIn("project_brand_assets", page_source)
        self.assertIn("Preview asset", page_source)
        self.assertIn(".themeEditorPreview", css_source)
        self.assertIn(".themePreviewCard", css_source)
        self.assertIn(".themeMetricStrip", css_source)
        self.assertIn(".themeColorField", css_source)
        self.assertIn(".brandAssetLibrary", css_source)
        self.assertIn(".brandAssetForm", css_source)
        self.assertIn(".assetActivateForm", css_source)
        self.assertIn(".inlineLink", css_source)

    def test_runtime_console_surfaces_report_history_management(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Report History", page_source)
        self.assertIn("recordRuntimeReportManagementEvent", page_source)
        self.assertIn("/v1/reports/runtime/${reportExportId}/management-events", page_source)
        self.assertIn("report_export_management_recorded", page_source)
        self.assertIn('name="report_export_id"', page_source)
        self.assertIn('name="status"', page_source)
        self.assertIn("client_ready", page_source)
        self.assertIn("Record status", page_source)
        self.assertIn("reportArtifactSignedUrlPath", page_source)
        self.assertIn("/signed-url", page_source)
        self.assertIn("Signed PDF URL", page_source)
        self.assertIn("Signed white-label URL", page_source)
        self.assertIn("HMAC signed URL endpoint", page_source)
        self.assertIn("Report Export Queue", page_source)
        self.assertIn("enqueueRuntimeReportExportJob", page_source)
        self.assertIn("updateRuntimeReportExportJobStatus", page_source)
        self.assertIn("/v1/report-export-jobs/runtime", page_source)
        self.assertIn("/v1/report-export-jobs/runtime/stats", page_source)
        self.assertIn("/v1/report-export-jobs/runtime/${jobId}/status", page_source)
        self.assertIn("report_export_job_queued", page_source)
        self.assertIn("report_export_job_status_updated", page_source)
        self.assertIn("RuntimeReportExportJobQueueStats", page_source)
        self.assertIn("Runtime Notifications", page_source)
        self.assertIn("RuntimeNotificationPage", page_source)
        self.assertIn("RuntimeNotificationSubscription", page_source)
        self.assertIn("RuntimeNotificationDelivery", page_source)
        self.assertIn("saveRuntimeNotificationSubscription", page_source)
        self.assertIn("updateRuntimeNotificationStatus", page_source)
        self.assertIn("/v1/runtime-notifications", page_source)
        self.assertIn("/v1/runtime-notification-subscriptions", page_source)
        self.assertIn("/v1/runtime-notification-deliveries", page_source)
        self.assertIn("/v1/runtime-notifications/${notificationId}/status", page_source)
        self.assertIn("runtime_notification_created", page_source)
        self.assertIn("runtime_notification_v1", page_source)
        self.assertIn("runtime_notification_subscription_saved", page_source)
        self.assertIn("runtime_notification_delivery_status_updated", page_source)
        self.assertIn("notificationSubscriptions", page_source)
        self.assertIn("notificationDeliveries", page_source)
        self.assertIn("Save subscription", page_source)
        self.assertIn('name="channel"', page_source)
        self.assertIn('value="slack"', page_source)
        self.assertIn('value="email"', page_source)
        self.assertIn("Slack Incoming Webhook URL", page_source)
        self.assertIn("mailto:ops@example.com", page_source)
        self.assertIn("slack_channel", page_source)
        self.assertIn("email_reply_to", page_source)
        self.assertIn("runtime_alert", page_source)
        self.assertIn("signing_secret_env", page_source)
        self.assertIn("GENO_NOTIFICATION_WEBHOOK_SIGNING_SECRET", page_source)
        self.assertIn("unread_count", page_source)
        self.assertIn("retryable_count", page_source)
        self.assertIn("expired_running_count", page_source)
        self.assertIn("dead_letter", page_source)
        self.assertIn("attempt_count", page_source)
        self.assertIn("lease_expires_at", page_source)
        self.assertIn("next_attempt_at", page_source)
        self.assertIn("Queue export", page_source)
        self.assertIn("Update job", page_source)
        self.assertIn(".reportManagementForm", css_source)
        self.assertIn(".reportExportJobForm", css_source)
        self.assertIn(".queueStatsGrid", css_source)

    def test_runtime_console_surfaces_project_member_management(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Project Members", page_source)
        self.assertIn("RuntimeProjectMember", page_source)
        self.assertIn("saveRuntimeProjectMember", page_source)
        self.assertIn("deleteRuntimeProjectMember", page_source)
        self.assertIn("/v1/project-members/runtime", page_source)
        self.assertIn('method: "DELETE"', page_source)
        self.assertIn("project_member_saved", page_source)
        self.assertIn("project_member_deleted", page_source)
        self.assertIn('name="user_id"', page_source)
        self.assertIn('name="role"', page_source)
        self.assertIn("project_members gate", page_source)
        self.assertIn(".projectMemberForm", css_source)
        self.assertIn(".projectMemberDeleteForm", css_source)
        self.assertIn(".textButton", css_source)

    def test_runtime_console_surfaces_runtime_alerts(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Runtime Alerts", page_source)
        self.assertIn("RuntimeAlert", page_source)
        self.assertIn("/v1/runtime-alerts", page_source)
        self.assertIn("runtime_alerts_v1", page_source)
        self.assertIn("evidence_refs", page_source)
        self.assertIn("related_actions", page_source)
        self.assertIn("management_events", page_source)
        self.assertIn("recordRuntimeAlertEvent", page_source)
        self.assertIn("enqueueRuntimeAlertNotifications", page_source)
        self.assertIn("runtimeAlertEventPath", page_source)
        self.assertIn("/v1/runtime-alerts/${alertId}/events", page_source)
        self.assertIn("/v1/runtime-alerts/notifications", page_source)
        self.assertIn("Queue alert notifications", page_source)
        self.assertIn("Record alert event", page_source)
        self.assertIn('value="acknowledged"', page_source)
        self.assertIn('value="resolved"', page_source)
        self.assertIn('value="snoozed"', page_source)
        self.assertIn('value="reopened"', page_source)
        self.assertIn('value="escalated"', page_source)
        self.assertIn("Alert query", page_source)
        self.assertIn(".alertGrid", css_source)
        self.assertIn(".alertItem", css_source)
        self.assertIn(".inlineForm", css_source)

    def test_runtime_console_surfaces_prompt_file_import(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Prompt CSV Import", page_source)
        self.assertIn("Prompt File Import", page_source)
        self.assertIn("importRuntimePromptsFile", page_source)
        self.assertIn("/v1/prompts/runtime/import.csv", page_source)
        self.assertIn("/v1/prompts/runtime/import.file", page_source)
        self.assertIn("/v1/prompts/runtime/imports", page_source)
        self.assertIn("RuntimePromptImportHistoryItem", page_source)
        self.assertIn("Prompt Import History", page_source)
        self.assertIn("Import query", page_source)
        self.assertIn(".csv or .xlsx", page_source)
        self.assertIn('name="prompt_file"', page_source)

    def test_runtime_console_surfaces_question_detail_matrix(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Question Detail", page_source)
        self.assertIn("questionEvidence", page_source)
        self.assertIn("buildQuestionDetailRows", page_source)
        self.assertIn("Question coverage", page_source)
        self.assertIn("Question evidence query", page_source)
        self.assertIn("Missing platforms", page_source)
        self.assertIn(".questionTable", css_source)
        self.assertIn(".questionRow", css_source)
        self.assertIn(".coverageBadge", css_source)
        self.assertIn(".coverage-platform_gap", css_source)

    def test_runtime_console_surfaces_human_review_trail(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Human Review Trail", page_source)
        self.assertIn("Review Queue", page_source)
        self.assertIn("submitHumanReview", page_source)
        self.assertIn("/v1/human-reviews/runtime", page_source)
        self.assertIn("/v1/human-reviews/runtime/queue", page_source)
        self.assertIn("RuntimeHumanReviewQueueItem", page_source)
        self.assertIn("Queue query", page_source)
        self.assertIn("human_review_recorded", page_source)
        self.assertIn("content_draft_review_status_updated", page_source)
        self.assertIn("Draft audit", page_source)
        self.assertIn("human_review_v1", page_source)
        self.assertIn("approved_for_report", page_source)
        self.assertIn(".humanReviewGrid", css_source)
        self.assertIn(".humanReviewForm", css_source)

    def test_runtime_console_surfaces_pgvector_knowledge_search(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("pgvector Knowledge Search", page_source)
        self.assertIn("/v1/knowledge-facts/runtime/search", page_source)
        self.assertIn("RuntimeKnowledgeSearch", page_source)
        self.assertIn("knowledge_fact_embeddings_indexed", page_source)
        self.assertIn("fixture-knowledge-embedding-v1", page_source)


if __name__ == "__main__":
    unittest.main()
