from __future__ import annotations

from pathlib import Path
import unittest


class WebConsoleContractsTest(unittest.TestCase):
    def test_runtime_console_contains_traceability_links_and_graph_maps(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        traceability_source = Path("apps/web/app/traceability/page.tsx").read_text(encoding="utf-8")
        interactive_map_source = Path("apps/web/app/traceability/InteractiveTraceabilityMap.tsx").read_text(encoding="utf-8")

        self.assertIn("function CitationGraphMap", page_source)
        self.assertIn("function TraceabilityMap", page_source)
        self.assertIn("function NodeLink", page_source)
        self.assertIn('id={anchorId("traceability-map", "runtime")}', page_source)
        self.assertIn('id={anchorId("source-node", item.node.id)}', page_source)
        self.assertIn('id={anchorId("answer-run", run.answer_run.id)}', page_source)
        self.assertIn('href={anchorHref("answer-run", run.answer_run.id)}', page_source)
        self.assertIn('href={anchorHref("source-node", item.node.id)}', page_source)
        self.assertIn("Open traceability detail", page_source)
        self.assertIn("/traceability", page_source)
        self.assertIn("Standalone runtime traceability map", traceability_source)
        self.assertIn('traceability: "/v1/traceability/runtime"', traceability_source)
        self.assertIn('graphs: "/v1/citation-graphs/runtime"', traceability_source)
        self.assertIn('projects: "/v1/projects/runtime"', traceability_source)
        self.assertIn("runtimePath(endpoints.traceability", traceability_source)
        self.assertIn('fixtureTraceability: "/v1/traceability/au/p0a-fixture"', traceability_source)
        self.assertIn('fixtureGraph: "/v1/citation-graphs/au/p0a-fixture"', traceability_source)
        self.assertIn("Fixture fallback", traceability_source)
        self.assertIn("normalizeFixtureTraceability", traceability_source)
        self.assertIn("normalizeFixtureGraph", traceability_source)
        self.assertIn("TraceabilityWorkbenchFilters", traceability_source)
        self.assertIn("buildTraceabilityWorkbench", traceability_source)
        self.assertIn("buildInteractiveTraceabilityGraph", traceability_source)
        self.assertIn("InteractiveTraceabilityMap", traceability_source)
        self.assertIn("Interactive nodes", traceability_source)
        self.assertIn("Interactive edges", traceability_source)
        self.assertIn("Filtered nodes", traceability_source)
        self.assertIn("Data mode", traceability_source)
        self.assertIn("Traceability Workbench", traceability_source)
        self.assertIn("URL-shareable filters", traceability_source)
        self.assertIn('name="q"', traceability_source)
        self.assertIn('name="node_type"', traceability_source)
        self.assertIn('name="platform"', traceability_source)
        self.assertIn('name="source_type"', traceability_source)
        self.assertIn('name="gap_type"', traceability_source)
        self.assertIn("workbenchFilters", traceability_source)
        self.assertIn("visibleTotal", traceability_source)
        self.assertIn("traceabilityWorkbenchForm", traceability_source)
        self.assertIn("traceabilityWorkbenchSummary", traceability_source)
        self.assertIn("traceabilityFactPill", traceability_source)
        self.assertIn("project_id", traceability_source)
        self.assertIn('id={anchorId("answer-run", run.answer_run.id)}', traceability_source)
        self.assertIn('id={anchorId("source-node", item.node.id)}', traceability_source)
        self.assertIn('id={anchorId("action", action.id || action.title)}', traceability_source)
        self.assertIn('id={anchorId("content-draft", item.draft.id || item.draft.title)}', traceability_source)
        self.assertIn('href={anchorHref(node.kind, node.value)}', traceability_source)
        self.assertIn("Back to console", traceability_source)
        self.assertIn('"use client"', interactive_map_source)
        self.assertIn("InteractiveTraceabilityNode", interactive_map_source)
        self.assertIn("InteractiveTraceabilityEdge", interactive_map_source)
        self.assertIn("interactiveTraceabilityToolbar", interactive_map_source)
        self.assertIn("interactiveTraceabilityViewport", interactive_map_source)
        self.assertIn("computeForceDirectedLayout", interactive_map_source)
        self.assertIn("forceLayoutIterations", interactive_map_source)
        self.assertIn("runForceLayout", interactive_map_source)
        self.assertIn("resetNodePositions", interactive_map_source)
        self.assertIn("nodeDragRef", interactive_map_source)
        self.assertIn("handleNodePointerDown", interactive_map_source)
        self.assertIn("handleNodePointerMove", interactive_map_source)
        self.assertIn("handleNodePointerEnd", interactive_map_source)
        self.assertIn("Run force-directed layout", interactive_map_source)
        self.assertIn("Reset node positions", interactive_map_source)
        self.assertIn("onWheel={handleWheel}", interactive_map_source)
        self.assertIn("onPointerDown={handlePointerDown}", interactive_map_source)
        self.assertIn("onPointerMove={handlePointerMove}", interactive_map_source)
        self.assertIn("handleNodeKeyDown", interactive_map_source)
        self.assertIn("Open node", interactive_map_source)

    def test_runtime_console_styles_highlight_deep_link_targets(self) -> None:
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn(".graphCanvas", css_source)
        self.assertIn(".traceMapCanvas", css_source)
        self.assertIn(".nodeLink", css_source)
        self.assertIn(".traceabilityPage", css_source)
        self.assertIn(".traceabilityTwoColumn", css_source)
        self.assertIn(".traceabilityStandaloneMap", css_source)
        self.assertIn(".traceabilityWorkbenchForm", css_source)
        self.assertIn(".traceabilityWorkbenchSummary", css_source)
        self.assertIn(".traceabilityFactPill", css_source)
        self.assertIn(".interactiveTraceabilityMap", css_source)
        self.assertIn(".interactiveTraceabilityToolbar", css_source)
        self.assertIn(".interactiveTraceabilityViewport", css_source)
        self.assertIn(".interactiveTraceabilityNodeSelected", css_source)
        self.assertIn(".interactiveTraceabilityNodeDragging", css_source)
        self.assertIn(".interactiveTraceabilityInspector", css_source)
        self.assertIn(".noticeMini", css_source)
        self.assertIn(":target", css_source)

    def test_runtime_console_discloses_report_method_boundaries(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Method Disclosure", page_source)
        self.assertIn("Google coverage", page_source)
        self.assertIn("Google gate", page_source)
        self.assertIn("API/browser fidelity", page_source)
        self.assertIn("Trigger denominator", page_source)
        self.assertIn("Mention denominator", page_source)
        self.assertIn("Recommendation denominator", page_source)
        self.assertIn("Attempted records", page_source)
        self.assertIn("Surface-triggered records", page_source)
        self.assertIn("Evidence trigger rate", page_source)
        self.assertIn("score_rate_denominators", page_source)
        self.assertIn("Access distribution", page_source)
        self.assertIn("Google remains outside the main scoring denominator", page_source)

    def test_runtime_console_surfaces_api_browser_fidelity_checks(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn('fidelityChecks: "/v1/fidelity-checks/runtime"', page_source)
        self.assertIn('fidelityExport: "/v1/fidelity-checks/runtime/export.csv"', page_source)
        self.assertIn('fidelityTrend: "/v1/fidelity-checks/runtime/trend"', page_source)
        self.assertIn("RuntimeFidelityCheck", page_source)
        self.assertIn("RuntimeFidelityTrend", page_source)
        self.assertIn("fidelityExportUrl", page_source)
        self.assertIn("api_browser_fidelity_checked", page_source)
        self.assertIn("Fidelity audit", page_source)
        self.assertIn("Fidelity query", page_source)
        self.assertIn("Fidelity CSV", page_source)
        self.assertIn("Download fidelity CSV", page_source)
        self.assertIn("Fidelity trend", page_source)
        self.assertIn("Trend query", page_source)
        self.assertIn("Payload hash", page_source)

    def test_runtime_console_surfaces_au_launch_status_gate(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn('launchStatus: "/v1/launch-status/au"', page_source)
        self.assertIn('launchRemediationPlan: "/v1/launch-remediation-plan/au"', page_source)
        self.assertIn('p0aEnvironmentChecklist: "/v1/p0a-environment-checklist/au"', page_source)
        self.assertIn('p0aExecutionChecklist: "/v1/p0a-execution-checklist/au"', page_source)
        self.assertIn('p0aCredentialRequest: "/v1/p0a-credential-request/au"', page_source)
        self.assertIn('p0aCredentialFulfillment: "/v1/p0a-credential-fulfillment/au"', page_source)
        self.assertIn('p0aCredentialClearance: "/v1/p0a-credential-clearance/au"', page_source)
        self.assertIn('p0aCredentialUpdateReceipt: "/v1/p0a-credential-update-receipt/au"', page_source)
        self.assertIn('p0aRealBatchRequest: "/v1/p0a-real-batch-request/au"', page_source)
        self.assertIn('p0aRealBatchFulfillment: "/v1/p0a-real-batch-fulfillment/au"', page_source)
        self.assertIn('p0aRealBatchClearance: "/v1/p0a-real-batch-clearance/au"', page_source)
        self.assertIn('p0bGoogleExecutionChecklist: "/v1/p0b-google-execution-checklist/au"', page_source)
        self.assertIn('p0bGoogleEnvironmentRequest: "/v1/p0b-google-environment-request/au"', page_source)
        self.assertIn('p0bGoogleEnvironmentFulfillment: "/v1/p0b-google-environment-fulfillment/au"', page_source)
        self.assertIn('p0bGoogleEnvironmentClearance: "/v1/p0b-google-environment-clearance/au"', page_source)
        self.assertIn('p0bGoogleManualBackfillRequest: "/v1/p0b-google-manual-backfill-request/au"', page_source)
        self.assertIn(
            'p0bGoogleManualBackfillFulfillment: "/v1/p0b-google-manual-backfill-fulfillment/au"',
            page_source,
        )
        self.assertIn(
            'p0bGoogleManualBackfillClearance: "/v1/p0b-google-manual-backfill-clearance/au"',
            page_source,
        )
        self.assertIn('p0bGooglePhaseExecutionRequest: "/v1/p0b-google-phase-execution-request/au"', page_source)
        self.assertIn(
            'p0bGooglePhaseExecutionFulfillment: "/v1/p0b-google-phase-execution-fulfillment/au"',
            page_source,
        )
        self.assertIn(
            'p0bGooglePhaseExecutionClearance: "/v1/p0b-google-phase-execution-clearance/au"',
            page_source,
        )
        self.assertIn('externalDependencyHandoff: "/v1/external-dependency-handoff/au"', page_source)
        self.assertIn('externalDependencyClearance: "/v1/external-dependency-clearance/au"', page_source)
        self.assertIn('broaderPlatformRegistry: "/v1/au-broader-platform-registry"', page_source)
        self.assertIn('retestSchedulerPlan: "/v1/au-retest-scheduler-plan"', page_source)
        self.assertIn('retestExecutionStatus: "/v1/au-retest-execution-status"', page_source)
        self.assertIn('handoffDossier: "/v1/handoff-dossier/au"', page_source)
        self.assertIn('customerHandoffReadiness: "/v1/customer-handoff-readiness/au"', page_source)
        self.assertIn('nextWorkItem: "/v1/next-work-item/au"', page_source)
        self.assertIn('deliveryProgress: "/v1/delivery-progress/au"', page_source)
        self.assertIn("type AuLaunchStatus", page_source)
        self.assertIn("type AuLaunchRemediationPlan", page_source)
        self.assertIn("type AuP0aEnvironmentChecklist", page_source)
        self.assertIn("type AuP0aExecutionChecklist", page_source)
        self.assertIn("type AuP0aCredentialRequest", page_source)
        self.assertIn("type AuP0aCredentialClearance", page_source)
        self.assertIn("type AuP0aCredentialUpdateReceipt", page_source)
        self.assertIn("type AuP0aRealBatchRequest", page_source)
        self.assertIn("type AuP0aRealBatchClearance", page_source)
        self.assertIn("type AuP0bGoogleExecutionChecklist", page_source)
        self.assertIn("type AuP0bGoogleEnvironmentRequest", page_source)
        self.assertIn("type AuP0bGoogleEnvironmentFulfillment", page_source)
        self.assertIn("type AuP0bGoogleManualBackfillRequest", page_source)
        self.assertIn("type AuP0bGoogleManualBackfillClearance", page_source)
        self.assertIn("type AuExternalDependencyHandoff", page_source)
        self.assertIn("type AuExternalDependencyClearance", page_source)
        self.assertIn("type AuBroaderPlatformRegistry", page_source)
        self.assertIn("type AuRetestSchedulerPlan", page_source)
        self.assertIn("type AuRetestExecutionStatus", page_source)
        self.assertIn("type AuHandoffDossier", page_source)
        self.assertIn("type AuCustomerHandoffReadiness", page_source)
        self.assertIn("type AuCustomerHandoffClearance", page_source)
        self.assertIn("type AuNextWorkItemPacket", page_source)
        self.assertIn("type AuDeliveryProgress", page_source)
        self.assertIn("AU Launch Gate", page_source)
        self.assertIn("ready_for_customer_report_handoff", page_source)
        self.assertIn("launch_status_hash", page_source)
        self.assertIn("remediation_plan_hash", page_source)
        self.assertIn("handoff_dossier_hash", page_source)
        self.assertIn("Handoff dossier", page_source)
        self.assertIn("handoff_posture", page_source)
        self.assertIn("customer_handoff_readiness_audit", page_source)
        self.assertIn("Customer readiness", page_source)
        self.assertIn("Auditability", page_source)
        self.assertIn("Blocked gate ids", page_source)
        self.assertIn("au_customer_handoff_readiness_audit_v1", page_source)
        self.assertIn("scripts/verify_au_handoff_dossier.py --require-customer-ready", page_source)
        self.assertIn("External dependency handoff", page_source)
        self.assertIn("external_dependency_handoff_hash", page_source)
        self.assertIn("next_dependency_item_id", page_source)
        self.assertIn("p0a_required_secret_missing_count", page_source)
        self.assertIn("p0b_google_required_input_missing_count", page_source)
        self.assertIn("clearance_sequence", page_source)
        self.assertIn("clearance_current_step_id", page_source)
        self.assertIn("Clearance", page_source)
        self.assertIn("Next clearance command", page_source)
        self.assertIn("Clearance dry-run", page_source)
        self.assertIn("clearance_execution_hash", page_source)
        self.assertIn("would_execute_step_count", page_source)
        self.assertIn("current_step_request_context", page_source)
        self.assertIn("current_recommended_sequence", page_source)
        self.assertIn("current_strict_gate_command", page_source)
        self.assertIn("Request context", page_source)
        self.assertIn("Request strict gate", page_source)
        self.assertIn("scripts/verify_au_external_dependency_clearance.py --require-handoff-ready", page_source)
        self.assertIn("paths.externalDependencyClearance", page_source)
        self.assertIn("Dry-run does not execute provider, DB, Google, manual, or customer handoff commands.", page_source)
        self.assertIn("dependencyGroupGrid", page_source)
        self.assertIn("group.next_command", page_source)
        self.assertIn("group.commands?.length", page_source)
        self.assertIn("group.blocking_reasons", page_source)
        self.assertIn("Blocked", page_source)
        self.assertIn("scripts/verify_au_external_dependency_handoff.py --require-ready", page_source)
        self.assertIn("paths.externalDependencyHandoff", page_source)
        self.assertIn("Lifecycle replay", page_source)
        self.assertIn("Lifecycle CSV", page_source)
        self.assertIn("Audit replay", page_source)
        self.assertIn("Audit CSV", page_source)
        self.assertIn("project_lifecycle_events_export", page_source)
        self.assertIn("runtime_audit_events_export", page_source)
        self.assertIn("/v1/projects/runtime/lifecycle-events/export.csv?project_id={project_id}", page_source)
        self.assertIn("/v1/audit-events/runtime/export.csv?project_id={project_id}", page_source)
        self.assertIn("external_dependency_clearance", page_source)
        self.assertIn("External clearance dry-run", page_source)
        self.assertIn("GET /v1/external-dependency-clearance/au", page_source)
        self.assertIn("Customer handoff readiness", page_source)
        self.assertIn("customer_handoff_readiness_hash", page_source)
        self.assertIn("customer_report_handoff_readiness_percent", page_source)
        self.assertIn("structural_auditability_percent", page_source)
        self.assertIn("GET /v1/customer-handoff-readiness/au", page_source)
        self.assertIn("make verify-au-customer-handoff-readiness", page_source)
        self.assertIn("paths.customerHandoffReadiness", page_source)
        self.assertIn("Customer handoff clearance", page_source)
        self.assertIn("customer_handoff_clearance_hash", page_source)
        self.assertIn("au_customer_handoff_clearance_v1", page_source)
        self.assertIn("GET /v1/customer-handoff-clearance/au", page_source)
        self.assertIn("make verify-au-customer-handoff-clearance", page_source)
        self.assertIn("scripts/verify_au_customer_handoff_clearance.py", page_source)
        self.assertIn("customer_handoff_clearance_ready", page_source)
        self.assertIn("p0a_credential_clearance_hash", page_source)
        self.assertIn("p0a_credentials_fulfilled", page_source)
        self.assertIn("p0a_credential_clearance_ready", page_source)
        self.assertIn("p0a_credential_missing_required_count", page_source)
        self.assertIn("p0a_real_batch_clearance_hash", page_source)
        self.assertIn("p0a_real_batches_fulfilled", page_source)
        self.assertIn("p0a_real_batch_clearance_ready", page_source)
        self.assertIn("p0a_real_batch_missing_required_count", page_source)
        self.assertIn("P0a real batch hash", page_source)
        self.assertIn("GET /v1/p0a-real-batch-clearance/au", page_source)
        self.assertIn("p0b_google_environment_clearance_hash", page_source)
        self.assertIn("p0b_google_environment_clearance_ready", page_source)
        self.assertIn("p0b_google_manual_backfill_clearance_hash", page_source)
        self.assertIn("p0b_google_manual_backfill_clearance_ready", page_source)
        self.assertIn("p0b_google_manual_backfill_coverage_complete", page_source)
        self.assertIn("p0b_google_manual_backfill_content_complete", page_source)
        self.assertIn("p0b_google_manual_backfill_missing_answer_line_count", page_source)
        self.assertIn("P0b manual missing answer/citation/asset", page_source)
        self.assertIn("p0b_google_phase_execution_clearance_hash", page_source)
        self.assertIn("p0b_google_phase_execution_clearance_ready", page_source)
        self.assertIn("P0b environment hash", page_source)
        self.assertIn("P0b manual hash", page_source)
        self.assertIn("P0b phase hash", page_source)
        self.assertIn("GET /v1/p0b-google-environment-clearance/au", page_source)
        self.assertIn("GET /v1/p0b-google-manual-backfill-clearance/au", page_source)
        self.assertIn("GET /v1/p0b-google-phase-execution-clearance/au", page_source)
        self.assertIn("P0a clearance hash", page_source)
        self.assertIn("customerHandoffClearanceItems", page_source)
        self.assertIn("customerHandoffClearanceSteps", page_source)
        self.assertIn("customerHandoffClearanceValidation", page_source)
        self.assertIn("paths.customerHandoffClearance", page_source)
        self.assertIn("Customer handoff package", page_source)
        self.assertIn("customer_handoff_package_hash", page_source)
        self.assertIn("au_customer_handoff_package_v1", page_source)
        self.assertIn("GET /v1/customer-handoff-package/au", page_source)
        self.assertIn("GET /v1/p0a-credential-update-receipt/au", page_source)
        self.assertIn("make verify-au-customer-handoff-package", page_source)
        self.assertIn("scripts/verify_au_customer_handoff_package.py", page_source)
        self.assertIn("customerHandoffPackageSummary", page_source)
        self.assertIn("topCustomerHandoffPackageIndex", page_source)
        self.assertIn("p0a_credential_update_receipt_hash", page_source)
        self.assertIn("p0a_credential_update_receipt", page_source)
        self.assertIn("Credential receipt hash", page_source)
        self.assertIn("paths.customerHandoffPackage", page_source)
        self.assertIn("AU delivery progress", page_source)
        self.assertIn("delivery_progress_hash", page_source)
        self.assertIn("engineering_progress_percent", page_source)
        self.assertIn("blocked_progress_gate_ids", page_source)
        self.assertIn("p0a_credential_missing_required", page_source)
        self.assertIn("P0a missing keys", page_source)
        self.assertIn("p0a_real_batch_missing_required", page_source)
        self.assertIn("Next P0a real batch phase", page_source)
        self.assertIn("p0b_google_environment_missing_required", page_source)
        self.assertIn("p0b_google_manual_backfill_missing_required", page_source)
        self.assertIn("P0b manual prompt-city", page_source)
        self.assertIn("P0b manual verification action", page_source)
        self.assertIn("p0b_google_phase_execution_missing_required", page_source)
        self.assertIn("Next P0b phase", page_source)
        self.assertIn("GET /v1/delivery-progress/au", page_source)
        self.assertIn("GET /v1/p0a-credential-clearance/au", page_source)
        self.assertIn("make verify-au-delivery-progress", page_source)
        self.assertIn("paths.deliveryProgress", page_source)
        self.assertIn("Next work item packet", page_source)
        self.assertIn("next_work_item_packet_hash", page_source)
        self.assertIn("au_next_work_item_packet_v1", page_source)
        self.assertIn("execution_context", page_source)
        self.assertIn("linked_request_packet_id", page_source)
        self.assertIn("linked_request_artifact_type", page_source)
        self.assertIn("linked_dependency_group_id", page_source)
        self.assertIn("p0a_credential_request", page_source)
        self.assertIn("nextWorkItemLinkedRequest", page_source)
        self.assertIn("nextWorkItemRecommendedSequence", page_source)
        self.assertIn("work_item_command_count", page_source)
        self.assertIn("group_verification_command_count", page_source)
        self.assertIn("group_evidence_output_count", page_source)
        self.assertIn("group_verification_commands", page_source)
        self.assertIn("combined_verification_commands", page_source)
        self.assertIn("Linked group", page_source)
        self.assertIn("Linked artifact", page_source)
        self.assertIn("Artifact strict gate", page_source)
        self.assertIn("Dependency group next", page_source)
        self.assertIn("Dependency group counts", page_source)
        self.assertIn("Fulfillment gate", page_source)
        self.assertIn("Dependency group source", page_source)
        self.assertIn("GET /v1/next-work-item/au", page_source)
        self.assertIn("make verify-au-next-work-item", page_source)
        self.assertIn("make verify-au-p0a-credential-request", page_source)
        self.assertIn("make verify-au-p0a-credential-fulfillment", page_source)
        self.assertIn("--require-fulfilled", page_source)
        self.assertIn("strict_gate_command", page_source)
        self.assertIn("paths.nextWorkItem", page_source)
        self.assertIn("Execution status", page_source)
        self.assertIn("Execution ready", page_source)
        self.assertIn("Comparison allowed", page_source)
        self.assertIn("Missing artifacts", page_source)
        self.assertIn("Status hash", page_source)
        self.assertIn("retestExecutionGrid", css_source)
        self.assertIn("retestExecutionWindow", css_source)
        self.assertIn(".clearanceDryRun", css_source)
        self.assertIn("Remediation plan", page_source)
        self.assertIn("P0a environment checklist", page_source)
        self.assertIn("P0a execution checklist", page_source)
        self.assertIn("p0a_env_file_hygiene_ready", page_source)
        self.assertIn("P0a env-file hygiene", page_source)
        self.assertIn("p0a_execution_checklist_hash", page_source)
        self.assertIn("Credential handoff", page_source)
        self.assertIn("P0a credential handoff", page_source)
        self.assertIn("credential_handoff_missing_required", page_source)
        self.assertIn("p0a_credential_handoff_missing_required_count", page_source)
        self.assertIn("P0a credential request packet", page_source)
        self.assertIn("p0a_credential_request_packet_hash", page_source)
        self.assertIn("GET /v1/p0a-credential-request/au", page_source)
        self.assertIn("make verify-au-p0a-credential-request", page_source)
        self.assertIn("missing_required_by_owner", page_source)
        self.assertIn("requestedP0aCredentials", page_source)
        self.assertIn("paths.p0aCredentialRequest", page_source)
        self.assertIn("P0a credential fulfillment", page_source)
        self.assertIn("p0a_credential_fulfillment_hash", page_source)
        self.assertIn("GET /v1/p0a-credential-fulfillment/au", page_source)
        self.assertIn("make verify-au-p0a-credential-fulfillment", page_source)
        self.assertIn("credentials_fulfilled", page_source)
        self.assertIn("p0aCredentialFulfillmentItems", page_source)
        self.assertIn("paths.p0aCredentialFulfillment", page_source)
        self.assertIn("P0a credential clearance", page_source)
        self.assertIn("p0a_credential_clearance_hash", page_source)
        self.assertIn("GET /v1/p0a-credential-clearance/au", page_source)
        self.assertIn("make verify-au-p0a-credential-clearance", page_source)
        self.assertIn("ready_for_next_clearance_step", page_source)
        self.assertIn("post_update_validation_sequence", page_source)
        self.assertIn("credential_update_contract", page_source)
        self.assertIn("Credential update contract", page_source)
        self.assertIn("p0aCredentialUpdateContract", page_source)
        self.assertIn("raw_values_allowed_in_artifacts", page_source)
        self.assertIn("allowed_update_surfaces", page_source)
        self.assertIn("strict_gate_commands", page_source)
        self.assertIn("p0aCredentialClearanceItems", page_source)
        self.assertIn("p0aCredentialClearanceSteps", page_source)
        self.assertIn("paths.p0aCredentialClearance", page_source)
        self.assertIn("P0a credential update receipt", page_source)
        self.assertIn("p0a_credential_update_receipt_hash", page_source)
        self.assertIn("GET /v1/p0a-credential-update-receipt/au", page_source)
        self.assertIn("make verify-au-p0a-credential-update-receipt", page_source)
        self.assertIn("credential_update_receipt_complete", page_source)
        self.assertIn("required_credential_records", page_source)
        self.assertIn("raw_value_recorded", page_source)
        self.assertIn("p0aCredentialUpdateReceiptRecords", page_source)
        self.assertIn("paths.p0aCredentialUpdateReceipt", page_source)
        self.assertIn("P0a real batch request packet", page_source)
        self.assertIn("p0a_real_batch_request_packet_hash", page_source)
        self.assertIn("au_p0a_real_batch_request_packet_v1", page_source)
        self.assertIn("GET /v1/p0a-real-batch-request/au", page_source)
        self.assertIn("make verify-au-p0a-real-batch-request", page_source)
        self.assertIn("scripts/verify_au_p0a_real_batch_request_packet.py", page_source)
        self.assertIn("P0a real batch fulfillment", page_source)
        self.assertIn("p0a_real_batch_fulfillment_hash", page_source)
        self.assertIn("au_p0a_real_batch_fulfillment_v1", page_source)
        self.assertIn("GET /v1/p0a-real-batch-fulfillment/au", page_source)
        self.assertIn("make verify-au-p0a-real-batch-fulfillment", page_source)
        self.assertIn("scripts/verify_au_p0a_real_batch_fulfillment.py", page_source)
        self.assertIn("p0aRealBatchFulfillmentItems", page_source)
        self.assertIn("P0a real batch clearance", page_source)
        self.assertIn("p0a_real_batch_clearance_hash", page_source)
        self.assertIn("GET /v1/p0a-real-batch-clearance/au", page_source)
        self.assertIn("make verify-au-p0a-real-batch-clearance", page_source)
        self.assertIn("blocked_by_prerequisite_step", page_source)
        self.assertIn("phase_clearance_items", page_source)
        self.assertIn("p0aRealBatchClearanceItems", page_source)
        self.assertIn("paths.p0aRealBatchClearance", page_source)
        self.assertIn("p0aRealBatchPhases", page_source)
        self.assertIn("p0aRealBatchBlockingReasons", page_source)
        self.assertIn("paths.p0aRealBatchRequest", page_source)
        self.assertIn("real_batch_phase_handoff_next_phase", page_source)
        self.assertIn("p0a_real_batch_phase_handoff_next_phase", page_source)
        self.assertIn("paths.p0aExecutionChecklist", page_source)
        self.assertIn("python3 scripts/verify_au_p0a_status_report.py --require-design-partner-ready", page_source)
        self.assertIn("P0b Google execution checklist", page_source)
        self.assertIn("google_execution_checklist_hash", page_source)
        self.assertIn("missing_selector_groups", page_source)
        self.assertIn("env_file_hygiene_ready", page_source)
        self.assertIn("Env-file hygiene", page_source)
        self.assertIn("p0b_google_env_file_hygiene_ready", page_source)
        self.assertIn("P0b env-file hygiene", page_source)
        self.assertIn("Environment handoff", page_source)
        self.assertIn("P0b environment handoff", page_source)
        self.assertIn("environment_handoff_missing_required", page_source)
        self.assertIn("p0b_google_environment_handoff_missing_required_count", page_source)
        self.assertIn("Manual backfill handoff", page_source)
        self.assertIn("P0b manual backfill handoff", page_source)
        self.assertIn("manual_backfill_handoff_missing_reasons", page_source)
        self.assertIn("manual_backfill_handoff_content_redacted", page_source)
        self.assertIn("p0b_google_manual_backfill_handoff_missing_reason_count", page_source)
        self.assertIn("Google phase handoff", page_source)
        self.assertIn("P0b Google phase handoff", page_source)
        self.assertIn("google_spike_phase_handoff_next_phase", page_source)
        self.assertIn("google_spike_phase_order", page_source)
        self.assertIn("p0b_google_spike_phase_handoff_blocked_phase_count", page_source)
        self.assertIn("paths.p0bGoogleExecutionChecklist", page_source)
        self.assertIn("python3 scripts/verify_au_p0b_google_evidence_package.py --require-google-main-scoring-allowed", page_source)
        self.assertIn("P0b Google environment request packet", page_source)
        self.assertIn("p0b_google_environment_request_packet_hash", page_source)
        self.assertIn("GET /v1/p0b-google-environment-request/au", page_source)
        self.assertIn("make verify-au-p0b-google-environment-request", page_source)
        self.assertIn("p0bGoogleEnvironmentRequestMissing", page_source)
        self.assertIn("cross_stage_reuse_hints", page_source)
        self.assertIn("p0bGoogleCrossStageReuseHints", page_source)
        self.assertIn("database_url_reuse_available", page_source)
        self.assertIn("source_p0a_env_report", page_source)
        self.assertIn("p0a_env_report_verifier", page_source)
        self.assertIn("DB reuse", page_source)
        self.assertIn("P0a env hash", page_source)
        self.assertIn("copy_raw_value_required", page_source)
        self.assertIn("p0bGoogleEnvironmentItems", page_source)
        self.assertIn("p0bGoogleSelectorItems", page_source)
        self.assertIn("paths.p0bGoogleEnvironmentRequest", page_source)
        self.assertIn("P0b Google environment fulfillment", page_source)
        self.assertIn("p0b_google_environment_fulfillment_hash", page_source)
        self.assertIn("GET /v1/p0b-google-environment-fulfillment/au", page_source)
        self.assertIn("make verify-au-p0b-google-environment-fulfillment", page_source)
        self.assertIn("environment_fulfilled", page_source)
        self.assertIn("p0bGoogleEnvironmentFulfillmentItems", page_source)
        self.assertIn("paths.p0bGoogleEnvironmentFulfillment", page_source)
        self.assertIn("P0b Google environment clearance", page_source)
        self.assertIn("p0b_google_environment_clearance_hash", page_source)
        self.assertIn("GET /v1/p0b-google-environment-clearance/au", page_source)
        self.assertIn("make verify-au-p0b-google-environment-clearance", page_source)
        self.assertIn("environment_clearance_ready", page_source)
        self.assertIn("p0bGoogleEnvironmentClearanceItems", page_source)
        self.assertIn("p0bGoogleEnvironmentClearanceSteps", page_source)
        self.assertIn("p0bGoogleEnvironmentClearanceValidation", page_source)
        self.assertIn("paths.p0bGoogleEnvironmentClearance", page_source)
        self.assertIn("P0b Google manual backfill request packet", page_source)
        self.assertIn("p0b_google_manual_backfill_request_packet_hash", page_source)
        self.assertIn("GET /v1/p0b-google-manual-backfill-request/au", page_source)
        self.assertIn("make verify-au-p0b-google-manual-backfill-request", page_source)
        self.assertIn("p0bGoogleManualBackfillRequestMissing", page_source)
        self.assertIn("p0bGoogleManualBackfillRequiredFields", page_source)
        self.assertIn("p0bGoogleManualBackfillOperatorRequirements", page_source)
        self.assertIn("paths.p0bGoogleManualBackfillRequest", page_source)
        self.assertIn("P0b Google manual backfill fulfillment", page_source)
        self.assertIn("p0b_google_manual_backfill_fulfillment_hash", page_source)
        self.assertIn("GET /v1/p0b-google-manual-backfill-fulfillment/au", page_source)
        self.assertIn("make verify-au-p0b-google-manual-backfill-fulfillment", page_source)
        self.assertIn("manual_backfill_fulfilled", page_source)
        self.assertIn("p0bGoogleManualBackfillFulfillmentItems", page_source)
        self.assertIn("paths.p0bGoogleManualBackfillFulfillment", page_source)
        self.assertIn("P0b Google manual backfill clearance", page_source)
        self.assertIn("p0b_google_manual_backfill_clearance_hash", page_source)
        self.assertIn("GET /v1/p0b-google-manual-backfill-clearance/au", page_source)
        self.assertIn("make verify-au-p0b-google-manual-backfill-clearance", page_source)
        self.assertIn("manual_backfill_clearance_ready", page_source)
        self.assertIn("p0bGoogleManualBackfillClearanceItems", page_source)
        self.assertIn("p0bGoogleManualBackfillClearanceSteps", page_source)
        self.assertIn("p0bGoogleManualBackfillClearanceValidation", page_source)
        self.assertIn("paths.p0bGoogleManualBackfillClearance", page_source)
        self.assertIn("P0b Google phase execution request packet", page_source)
        self.assertIn("p0b_google_phase_execution_request_packet_hash", page_source)
        self.assertIn("au_p0b_google_phase_execution_request_packet_v1", page_source)
        self.assertIn("GET /v1/p0b-google-phase-execution-request/au", page_source)
        self.assertIn("make verify-au-p0b-google-phase-execution-request", page_source)
        self.assertIn("scripts/verify_au_p0b_google_phase_execution_request_packet.py", page_source)
        self.assertIn("p0bGooglePhaseExecutionPhases", page_source)
        self.assertIn("p0bGooglePhaseExecutionBlockingReasons", page_source)
        self.assertIn("paths.p0bGooglePhaseExecutionRequest", page_source)
        self.assertIn("P0b Google phase execution fulfillment", page_source)
        self.assertIn("p0b_google_phase_execution_fulfillment_hash", page_source)
        self.assertIn("au_p0b_google_phase_execution_fulfillment_v1", page_source)
        self.assertIn("GET /v1/p0b-google-phase-execution-fulfillment/au", page_source)
        self.assertIn("make verify-au-p0b-google-phase-execution-fulfillment", page_source)
        self.assertIn("scripts/verify_au_p0b_google_phase_execution_fulfillment.py", page_source)
        self.assertIn("phase_execution_fulfilled", page_source)
        self.assertIn("p0bGooglePhaseExecutionFulfillmentItems", page_source)
        self.assertIn("paths.p0bGooglePhaseExecutionFulfillment", page_source)
        self.assertIn("P0b Google phase execution clearance", page_source)
        self.assertIn("p0b_google_phase_execution_clearance_hash", page_source)
        self.assertIn("au_p0b_google_phase_execution_clearance_v1", page_source)
        self.assertIn("GET /v1/p0b-google-phase-execution-clearance/au", page_source)
        self.assertIn("make verify-au-p0b-google-phase-execution-clearance", page_source)
        self.assertIn("scripts/verify_au_p0b_google_phase_execution_clearance.py", page_source)
        self.assertIn("phase_execution_clearance_ready", page_source)
        self.assertIn("p0bGooglePhaseExecutionClearanceItems", page_source)
        self.assertIn("p0bGooglePhaseExecutionClearanceSteps", page_source)
        self.assertIn("p0bGooglePhaseExecutionClearanceValidation", page_source)
        self.assertIn("paths.p0bGooglePhaseExecutionClearance", page_source)
        self.assertIn("Broader platform registry", page_source)
        self.assertIn("broader_platform_registry_hash", page_source)
        self.assertIn("gemini_search", page_source)
        self.assertIn("productreview_reviews", page_source)
        self.assertIn("paths.broaderPlatformRegistry", page_source)
        self.assertIn("AU Retest Scheduler Plan", page_source)
        self.assertIn("retest_scheduler_plan_hash", page_source)
        self.assertIn("planned_not_temporalized", page_source)
        self.assertIn("paths.retestSchedulerPlan", page_source)
        self.assertIn("environment_checklist_hash", page_source)
        self.assertIn("missing_required", page_source)
        self.assertIn("paths.p0aEnvironmentChecklist", page_source)
        self.assertIn("python3 scripts/verify_au_p0a_env_report.py --require-ready-environment", page_source)
        self.assertIn("next_work_item_id", page_source)
        self.assertIn("blocker_remediations", page_source)
        self.assertIn("p0a_design_partner", page_source)
        self.assertIn("p0b_google", page_source)
        self.assertIn("p0c_customer_report", page_source)
        self.assertIn("Remaining blockers", page_source)
        self.assertIn("Next action", page_source)
        self.assertIn("paths.launchStatus", page_source)
        self.assertIn("paths.launchRemediationPlan", page_source)
        self.assertIn("paths.handoffDossier", page_source)
        self.assertIn(".launchStatusPanel", css_source)
        self.assertIn(".launchStatusHeader", css_source)
        self.assertIn(".launchStageGrid", css_source)
        self.assertIn(".launchEvidenceGrid", css_source)
        self.assertIn(".launchBlockers", css_source)
        self.assertIn(".launchRemediation", css_source)
        self.assertIn(".p0aEnvironmentChecklist", css_source)
        self.assertIn(".p0bGoogleExecutionChecklist", css_source)
        self.assertIn(".broaderPlatformRegistry", css_source)
        self.assertIn(".retestSchedulerPlan", css_source)
        self.assertIn(".retestTimeline", css_source)
        self.assertIn(".retestWindow", css_source)
        self.assertIn(".platformRegistryGrid", css_source)
        self.assertIn(".platformCandidate", css_source)
        self.assertIn(".environmentChecklistGrid", css_source)
        self.assertIn(".handoffDossier", css_source)
        self.assertIn(".externalDependencyHandoff", css_source)
        self.assertIn(".clearanceStepGrid", css_source)
        self.assertIn(".clearanceStep", css_source)
        self.assertIn(".dependencyGroupGrid", css_source)
        self.assertIn(".dependencyGroup", css_source)
        self.assertIn(".handoffBoundary", css_source)
        self.assertIn(".remediationList", css_source)
        self.assertIn(".remediationItem", css_source)

    def test_runtime_console_surfaces_collection_run_quality(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn('collectionRuns: "/v1/collection-runs/runtime"', page_source)
        self.assertIn('collectionRunsExport: "/v1/collection-runs/runtime/export.csv"', page_source)
        self.assertIn("type CollectionRun", page_source)
        self.assertIn("collectionRunsExportUrl", page_source)
        self.assertIn("Collection Run Quality", page_source)
        self.assertIn("Collection query", page_source)
        self.assertIn("Collection CSV", page_source)
        self.assertIn("Download collection CSV", page_source)
        self.assertIn("Success rate", page_source)
        self.assertIn("Trigger rate", page_source)
        self.assertIn("Answer rate", page_source)
        self.assertIn("Total cost", page_source)
        self.assertIn("Avg cost/run", page_source)
        self.assertIn("Avg duration", page_source)
        self.assertIn("Duration", page_source)
        self.assertIn("duration_ms", page_source)
        self.assertIn("total_duration_ms", page_source)
        self.assertIn("average_duration_ms", page_source)
        self.assertIn("failure_summary", page_source)

    def test_runtime_console_surfaces_parser_comparison(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Parser agreement", page_source)
        self.assertIn("parser_comparison", page_source)
        self.assertIn("parser_ab_compare_v1", page_source)
        self.assertIn("parserComparisonText", page_source)
        self.assertIn("mismatches", page_source)
        self.assertIn("llm_call_log", page_source)
        self.assertIn("LLM call", page_source)

    def test_runtime_console_surfaces_score_weight_configuration(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Score Weights", page_source)
        self.assertIn("saveScoreWeightConfig", page_source)
        self.assertIn("/v1/score-weight-configs/runtime", page_source)
        self.assertIn("/v1/score-formulas/runtime", page_source)
        self.assertIn("Formula catalog", page_source)
        self.assertIn("Formula version", page_source)
        self.assertIn("Selected formula", page_source)
        self.assertIn("Formula status", page_source)
        self.assertIn("Formula note", page_source)
        self.assertIn("Supersedes", page_source)
        self.assertIn("component_weights_snapshot", page_source)
        self.assertIn("Weight snapshot", page_source)

    def test_runtime_console_surfaces_brand_logo_upload(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Logo Upload", page_source)
        self.assertIn("uploadProjectBrandLogo", page_source)
        self.assertIn("/v1/project-brand-kits/runtime/logo", page_source)
        self.assertIn('name="brand_logo"', page_source)
        self.assertIn('type="file"', page_source)
        self.assertIn("project_brand_logo_uploaded", page_source)
        self.assertIn("Theme Editor", page_source)
        self.assertIn("themeEditorPreview", page_source)
        self.assertIn("advanced white-label theme editor", page_source)
        self.assertIn("Template payload", page_source)
        self.assertIn('type="color"', page_source)
        self.assertIn("primary_color", page_source)
        self.assertIn("secondary_color", page_source)
        self.assertIn("project_brand_kit_saved", page_source)
        self.assertIn("Brand Assets", page_source)
        self.assertIn("RuntimeProjectBrandAssetVersion", page_source)
        self.assertIn("RuntimeProjectBrandAsset", page_source)
        self.assertIn("activateProjectBrandAssetVersion", page_source)
        self.assertIn("saveProjectBrandAsset", page_source)
        self.assertIn("updateProjectBrandAssetScanStatus", page_source)
        self.assertIn("/v1/project-brand-kits/runtime/assets", page_source)
        self.assertIn("/v1/project-brand-kits/runtime/assets/activate", page_source)
        self.assertIn("/v1/project-brand-assets/runtime", page_source)
        self.assertIn("/v1/project-brand-assets/runtime/${assetId}/scan-status", page_source)
        self.assertIn('name="asset_url"', page_source)
        self.assertIn('name="preview_url"', page_source)
        self.assertIn('name="scan_status"', page_source)
        self.assertIn("project_brand_asset_scan_recorded", page_source)
        self.assertIn("Asset Register", page_source)
        self.assertIn("Asset Library", page_source)
        self.assertIn("project_brand_asset_library_v1", page_source)
        self.assertIn("project_brand_assets", page_source)
        self.assertIn("Preview asset", page_source)
        self.assertIn(".themeEditorPreview", css_source)
        self.assertIn(".themePreviewCard", css_source)
        self.assertIn(".themeMetricStrip", css_source)
        self.assertIn(".themeColorField", css_source)
        self.assertIn(".brandAssetLibrary", css_source)
        self.assertIn(".brandAssetForm", css_source)
        self.assertIn(".assetActivateForm", css_source)
        self.assertIn(".inlineLink", css_source)

    def test_runtime_console_surfaces_report_history_management(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Report History", page_source)
        self.assertIn("recordRuntimeReportManagementEvent", page_source)
        self.assertIn("/v1/reports/runtime/${reportExportId}/management-events", page_source)
        self.assertIn("/v1/reports/runtime/management-events/export.csv", page_source)
        self.assertIn("reportManagementEventsExport", page_source)
        self.assertIn("report_export_management_recorded", page_source)
        self.assertIn('name="report_export_id"', page_source)
        self.assertIn('name="status"', page_source)
        self.assertIn("client_ready", page_source)
        self.assertIn("Record status", page_source)
        self.assertIn("Report management CSV", page_source)
        self.assertIn("Download report management CSV", page_source)
        self.assertIn("reportArtifactSignedUrlPath", page_source)
        self.assertIn("/signed-url", page_source)
        self.assertIn("Signed PDF URL", page_source)
        self.assertIn("Signed white-label URL", page_source)
        self.assertIn("HMAC signed URL endpoint", page_source)
        self.assertIn("Report Export Queue", page_source)
        self.assertIn("enqueueRuntimeReportExportJob", page_source)
        self.assertIn("updateRuntimeReportExportJobStatus", page_source)
        self.assertIn("/v1/report-export-jobs/runtime", page_source)
        self.assertIn("/v1/report-export-jobs/runtime/export.csv", page_source)
        self.assertIn("/v1/report-export-jobs/runtime/stats", page_source)
        self.assertIn("/v1/report-export-jobs/runtime/${jobId}/status", page_source)
        self.assertIn("/v1/action-plans/runtime/export.csv", page_source)
        self.assertIn("actionsExport", page_source)
        self.assertIn("Action Plan CSV", page_source)
        self.assertIn("Download action plan CSV", page_source)
        self.assertIn("report_export_job_queued", page_source)
        self.assertIn("report_export_job_status_updated", page_source)
        self.assertIn("RuntimeReportExportJobQueueStats", page_source)
        self.assertIn("Report Jobs CSV", page_source)
        self.assertIn("Download report jobs CSV", page_source)
        self.assertIn("reportJobsExport", page_source)
        self.assertIn("Runtime Notifications", page_source)
        self.assertIn("RuntimeNotificationPage", page_source)
        self.assertIn("RuntimeNotificationSubscription", page_source)
        self.assertIn("RuntimeNotificationDelivery", page_source)
        self.assertIn("RuntimeNotificationEmailFeedback", page_source)
        self.assertIn("RuntimeNotificationEmailSuppression", page_source)
        self.assertIn("saveRuntimeNotificationSubscription", page_source)
        self.assertIn("updateRuntimeNotificationStatus", page_source)
        self.assertIn("recordRuntimeNotificationEmailFeedback", page_source)
        self.assertIn("applyRuntimeNotificationEmailFeedbackSuppression", page_source)
        self.assertIn("applyRuntimeNotificationEmailFeedbackProjectSuppression", page_source)
        self.assertIn("saveRuntimeNotificationEmailSuppression", page_source)
        self.assertIn("/v1/runtime-notifications", page_source)
        self.assertIn("/v1/runtime-notifications/export.csv", page_source)
        self.assertIn("/v1/runtime-notification-subscriptions", page_source)
        self.assertIn("/v1/runtime-notification-subscriptions/export.csv", page_source)
        self.assertIn("/v1/runtime-notification-deliveries", page_source)
        self.assertIn("/v1/runtime-notification-deliveries/export.csv", page_source)
        self.assertIn("/v1/runtime-notification-email-feedback-events", page_source)
        self.assertIn("/v1/runtime-notification-email-suppressions", page_source)
        self.assertIn("/v1/runtime-notification-email-suppressions/export.csv", page_source)
        self.assertIn("/v1/runtime-notification-email-feedback-webhooks/geno", page_source)
        self.assertIn(
            "/v1/runtime-notification-email-feedback-events/${feedbackEventId}/suppress-recipient",
            page_source,
        )
        self.assertIn(
            "/v1/runtime-notification-email-feedback-events/${feedbackEventId}/project-suppression",
            page_source,
        )
        self.assertIn("/v1/runtime-notification-email-preferences/status", page_source)
        self.assertIn("/v1/runtime-notification-email-preferences/resubscribe", page_source)
        self.assertIn("/v1/runtime-notification-email-preferences/unsubscribe", page_source)
        self.assertIn("/v1/runtime-notification-deliveries/${deliveryId}/email-feedback", page_source)
        self.assertIn("/v1/runtime-notifications/${notificationId}/status", page_source)
        self.assertIn("runtime_notification_created", page_source)
        self.assertIn("runtime_notification_v1", page_source)
        self.assertIn("runtime_notification_subscription_saved", page_source)
        self.assertIn("runtime_notification_delivery_status_updated", page_source)
        self.assertIn("runtime_notification_email_feedback_recorded", page_source)
        self.assertIn("runtime_notification_email_feedback_suppression_applied", page_source)
        self.assertIn("runtime_notification_email_feedback_project_suppression_applied", page_source)
        self.assertIn("runtime_notification_email_suppression_saved", page_source)
        self.assertIn("runtime_notification_email_suppression_v1", page_source)
        self.assertIn("Project email suppression", page_source)
        self.assertIn("Save project suppression", page_source)
        self.assertIn("Download notification CSV", page_source)
        self.assertIn("Download subscription CSV", page_source)
        self.assertIn("Download delivery CSV", page_source)
        self.assertIn("Download suppression CSV", page_source)
        self.assertIn("Subscription CSV", page_source)
        self.assertIn("Delivery CSV", page_source)
        self.assertIn("Suppression CSV", page_source)
        self.assertIn("Notification CSV", page_source)
        self.assertIn("Suppression API", page_source)
        self.assertIn("Project suppressions", page_source)
        self.assertIn("Preference status API", page_source)
        self.assertIn("Resubscribe API", page_source)
        self.assertIn("Unsubscribe API", page_source)
        self.assertIn("notificationEmailPreferenceStatus", page_source)
        self.assertIn("notificationEmailPreferenceResubscribe", page_source)
        self.assertIn("notificationEmailPreferenceUnsubscribe", page_source)
        self.assertIn("notificationsExport", page_source)
        self.assertIn("notificationSubscriptions", page_source)
        self.assertIn("notificationDeliveries", page_source)
        self.assertIn("notificationEmailFeedback", page_source)
        self.assertIn("notificationEmailSuppressions", page_source)
        self.assertIn("Save subscription", page_source)
        self.assertIn("Record feedback", page_source)
        self.assertIn("Apply suppression", page_source)
        self.assertIn('name="source_ref"', page_source)
        self.assertIn('value="provider"', page_source)
        self.assertIn("Email feedback", page_source)
        self.assertIn("Feedback API", page_source)
        self.assertIn("recipient_hash", page_source)
        self.assertIn("provider_event_id_hash", page_source)
        self.assertIn('name="channel"', page_source)
        self.assertIn('value="slack"', page_source)
        self.assertIn('value="email"', page_source)
        self.assertIn("Slack Incoming Webhook URL", page_source)
        self.assertIn("mailto:ops@example.com", page_source)
        self.assertIn("slack_channel", page_source)
        self.assertIn("email_reply_to", page_source)
        self.assertIn("email_unsubscribe_url", page_source)
        self.assertIn("email_unsubscribe_mailto", page_source)
        self.assertIn("email_preferences_url", page_source)
        self.assertIn("email_suppressed_recipients", page_source)
        self.assertIn("https://app.example.com/notifications/unsubscribe", page_source)
        self.assertIn("https://app.example.com/notifications/preferences", page_source)
        self.assertIn("muted@example.com", page_source)
        self.assertIn("runtime_alert", page_source)
        self.assertIn("signing_secret_env", page_source)
        self.assertIn("signing_secret_key_id", page_source)
        self.assertIn("previous_signing_secret_env", page_source)
        self.assertIn("GENO_NOTIFICATION_WEBHOOK_SIGNING_SECRET_PREVIOUS", page_source)
        self.assertIn("GENO_NOTIFICATION_WEBHOOK_SIGNING_SECRET", page_source)
        self.assertIn("unread_count", page_source)
        self.assertIn("retryable_count", page_source)
        self.assertIn("expired_running_count", page_source)
        self.assertIn("dead_letter", page_source)
        self.assertIn("attempt_count", page_source)
        self.assertIn("lease_expires_at", page_source)
        self.assertIn("next_attempt_at", page_source)
        self.assertIn("Queue export", page_source)
        self.assertIn("Update job", page_source)
        self.assertIn(".reportManagementForm", css_source)
        self.assertIn(".reportExportJobForm", css_source)
        self.assertIn(".queueStatsGrid", css_source)

    def test_runtime_console_surfaces_project_member_management(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Project Members", page_source)
        self.assertIn("RuntimeProjectMember", page_source)
        self.assertIn("RuntimeProjectMemberInvitation", page_source)
        self.assertIn("RuntimeProjectLifecycleEvent", page_source)
        self.assertIn("updateRuntimeProject", page_source)
        self.assertIn("actionRuntimeProject", page_source)
        self.assertIn("saveRuntimeProjectMember", page_source)
        self.assertIn("deleteRuntimeProjectMember", page_source)
        self.assertIn("createRuntimeProjectMemberInvitation", page_source)
        self.assertIn("actionRuntimeProjectMemberInvitation", page_source)
        self.assertIn("emailRuntimeProjectMemberInvitation", page_source)
        self.assertIn("acceptRuntimeProjectMemberInvitation", page_source)
        self.assertIn("/v1/project-members/runtime", page_source)
        self.assertIn("/v1/projects/runtime/action", page_source)
        self.assertIn("/v1/projects/runtime/lifecycle-events", page_source)
        self.assertIn("/v1/projects/runtime/lifecycle-events/export.csv", page_source)
        self.assertIn("projectLifecycleExport", page_source)
        self.assertIn("/v1/audit-events/runtime", page_source)
        self.assertIn("/v1/audit-events/runtime/export.csv", page_source)
        self.assertIn("auditEventsExport", page_source)
        self.assertIn("/v1/project-members/runtime/export.csv", page_source)
        self.assertIn("projectMembersExport", page_source)
        self.assertIn('method: "PATCH"', page_source)
        self.assertIn('method: "POST"', page_source)
        self.assertIn("/v1/project-member-invitations/runtime", page_source)
        self.assertIn("/v1/project-member-invitations/runtime/export.csv", page_source)
        self.assertIn("projectMemberInvitationsExport", page_source)
        self.assertIn("/v1/project-member-invitations/runtime/action", page_source)
        self.assertIn("/v1/project-member-invitations/runtime/email", page_source)
        self.assertIn("/v1/project-member-invitations/runtime/accept", page_source)
        self.assertIn('method: "DELETE"', page_source)
        self.assertIn("project_member_saved", page_source)
        self.assertIn("project_updated", page_source)
        self.assertIn("project_archived", page_source)
        self.assertIn("project_restored", page_source)
        self.assertIn("project_bootstrap_created", page_source)
        self.assertIn("project_member_deleted", page_source)
        self.assertIn("project_member_invitation_created", page_source)
        self.assertIn("project_member_invitation_email_sent", page_source)
        self.assertIn("project_member_invitation_accepted", page_source)
        self.assertIn("project_member_invitation_revoked", page_source)
        self.assertIn("project_member_invitation_expired", page_source)
        self.assertIn("Email invite", page_source)
        self.assertIn("Archive project", page_source)
        self.assertIn("Restore project", page_source)
        self.assertIn("Project Lifecycle", page_source)
        self.assertIn("Download lifecycle CSV", page_source)
        self.assertIn("Lifecycle export", page_source)
        self.assertIn("Project Audit Trail", page_source)
        self.assertIn("Download audit CSV", page_source)
        self.assertIn("Audit export", page_source)
        self.assertIn("Download members CSV", page_source)
        self.assertIn("Download invitations CSV", page_source)
        self.assertIn("Members CSV", page_source)
        self.assertIn("Invitations CSV", page_source)
        self.assertIn("Accept invite", page_source)
        self.assertIn("Revoke invite", page_source)
        self.assertIn("Expire invite", page_source)
        self.assertIn('name="user_id"', page_source)
        self.assertIn('name="invitation_id"', page_source)
        self.assertIn('name="email"', page_source)
        self.assertIn('name="role"', page_source)
        self.assertIn('name="status"', page_source)
        self.assertIn("project_members gate", page_source)
        self.assertIn(".projectLifecycleActions", css_source)
        self.assertIn(".projectLifecycleHistory", css_source)
        self.assertIn(".projectUpdateForm", css_source)
        self.assertIn(".projectMemberForm", css_source)
        self.assertIn(".projectMemberDeleteForm", css_source)
        self.assertIn(".inlineActions", css_source)
        self.assertIn(".inlineForm", css_source)

    def test_invite_accept_page_exchanges_token_without_login_assumption(self) -> None:
        page_source = Path("apps/web/app/invite/accept/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("InviteAcceptPage", page_source)
        self.assertIn("acceptProjectInvitation", page_source)
        self.assertIn("GENO_WEB_INVITE_ACCEPT_AUTO_SUBMIT", page_source)
        self.assertIn("/v1/project-member-invitations/runtime/accept", page_source)
        self.assertIn('name="invitation_id"', page_source)
        self.assertIn('name="invite_token"', page_source)
        self.assertIn("project_member_invitation_accepted", page_source)
        self.assertIn("Accept invitation", page_source)
        self.assertIn(".inviteShell", css_source)
        self.assertIn(".inviteAcceptForm", css_source)
        self.assertIn(".inviteResult", css_source)
        self.assertIn(".textButton", css_source)

    def test_email_preferences_page_reads_and_updates_manage_token(self) -> None:
        page_source = Path("apps/web/app/notifications/preferences/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("EmailNotificationPreferencesPage", page_source)
        self.assertIn("fetchEmailPreferenceStatus", page_source)
        self.assertIn("updateEmailPreference", page_source)
        self.assertIn("/v1/runtime-notification-email-preferences/status", page_source)
        self.assertIn("/v1/runtime-notification-email-preferences/resubscribe", page_source)
        self.assertIn("/v1/runtime-notification-email-preferences/unsubscribe", page_source)
        self.assertIn('name="token"', page_source)
        self.assertIn('name="action"', page_source)
        self.assertIn("runtime_notification_email_preference_status_v1", page_source)
        self.assertIn("Resubscribe", page_source)
        self.assertIn("Unsubscribe", page_source)
        self.assertIn(".preferenceShell", css_source)
        self.assertIn(".preferenceActionForm", css_source)
        self.assertIn(".preferenceAuditList", css_source)

    def test_runtime_console_surfaces_runtime_alerts(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Runtime Alerts", page_source)
        self.assertIn("RuntimeAlert", page_source)
        self.assertIn("/v1/runtime-alerts", page_source)
        self.assertIn("runtime_alerts_v1", page_source)
        self.assertIn("evidence_refs", page_source)
        self.assertIn("related_actions", page_source)
        self.assertIn("management_events", page_source)
        self.assertIn("recordRuntimeAlertEvent", page_source)
        self.assertIn("enqueueRuntimeAlertNotifications", page_source)
        self.assertIn("runtimeAlertEventPath", page_source)
        self.assertIn("/v1/runtime-alerts/export.csv", page_source)
        self.assertIn("alertsExport", page_source)
        self.assertIn("/v1/runtime-alerts/${alertId}/events", page_source)
        self.assertIn("/v1/runtime-alerts/notifications", page_source)
        self.assertIn("Queue alert notifications", page_source)
        self.assertIn("Record alert event", page_source)
        self.assertIn('value="acknowledged"', page_source)
        self.assertIn('value="resolved"', page_source)
        self.assertIn('value="snoozed"', page_source)
        self.assertIn('value="reopened"', page_source)
        self.assertIn('value="escalated"', page_source)
        self.assertIn("Alert query", page_source)
        self.assertIn("Alert CSV", page_source)
        self.assertIn("Download alert CSV", page_source)
        self.assertIn(".alertGrid", css_source)
        self.assertIn(".alertItem", css_source)
        self.assertIn(".inlineForm", css_source)

    def test_runtime_console_surfaces_prompt_file_import(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Prompt CSV Import", page_source)
        self.assertIn("Prompt File Import", page_source)
        self.assertIn('promptsExport: "/v1/prompts/runtime/export.csv"', page_source)
        self.assertIn("Prompt CSV", page_source)
        self.assertIn("Download prompt CSV", page_source)
        self.assertIn("importRuntimePromptsFile", page_source)
        self.assertIn("/v1/prompts/runtime/import.csv", page_source)
        self.assertIn("/v1/prompts/runtime/import.file", page_source)
        self.assertIn("/v1/prompts/runtime/imports", page_source)
        self.assertIn("RuntimePromptImportHistoryItem", page_source)
        self.assertIn("Prompt Import History", page_source)
        self.assertIn("Import query", page_source)
        self.assertIn(".csv or .xlsx", page_source)
        self.assertIn('name="prompt_file"', page_source)

    def test_runtime_console_surfaces_question_detail_matrix(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Question Detail", page_source)
        self.assertIn("questionEvidence", page_source)
        self.assertIn("buildQuestionDetailRows", page_source)
        self.assertIn("Question coverage", page_source)
        self.assertIn("Question evidence query", page_source)
        self.assertIn("Missing platforms", page_source)
        self.assertIn(".questionTable", css_source)
        self.assertIn(".questionRow", css_source)
        self.assertIn(".coverageBadge", css_source)
        self.assertIn(".coverage-platform_gap", css_source)

    def test_runtime_console_surfaces_human_review_trail(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Human Review Trail", page_source)
        self.assertIn("Review Queue", page_source)
        self.assertIn("submitHumanReview", page_source)
        self.assertIn("/v1/human-reviews/runtime", page_source)
        self.assertIn("/v1/human-reviews/runtime/export.csv", page_source)
        self.assertIn("/v1/human-reviews/runtime/queue", page_source)
        self.assertIn("humanReviewsExport", page_source)
        self.assertIn("RuntimeHumanReviewQueueItem", page_source)
        self.assertIn("Review CSV", page_source)
        self.assertIn("Queue query", page_source)
        self.assertIn("Download review CSV", page_source)
        self.assertIn("human_review_recorded", page_source)
        self.assertIn("content_draft_review_status_updated", page_source)
        self.assertIn("Draft audit", page_source)
        self.assertIn("human_review_v1", page_source)
        self.assertIn("approved_for_report", page_source)
        self.assertIn(".humanReviewGrid", css_source)
        self.assertIn(".humanReviewForm", css_source)

    def test_runtime_console_surfaces_score_contribution_export(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Score Contributions", page_source)
        self.assertIn('scores: "/v1/visibility-scores/runtime"', page_source)
        self.assertIn('scoresExport: "/v1/visibility-scores/runtime/export.csv"', page_source)
        self.assertIn("scoreSnapshotsExportUrl", page_source)
        self.assertIn("Score query", page_source)
        self.assertIn("Score CSV", page_source)
        self.assertIn("Download score CSV", page_source)

    def test_runtime_console_surfaces_citation_graph_export(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Citation Graph & Competitors", page_source)
        self.assertIn('graphs: "/v1/citation-graphs/runtime"', page_source)
        self.assertIn('graphsExport: "/v1/citation-graphs/runtime/export.csv"', page_source)
        self.assertIn("citationGraphsExportUrl", page_source)
        self.assertIn("Graph query", page_source)
        self.assertIn("Graph CSV", page_source)
        self.assertIn("Download graph CSV", page_source)

    def test_runtime_console_surfaces_entity_alias_batch_review_queue(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Bulk Alias Review Queue", page_source)
        self.assertIn("confirmEntityAliasBatch", page_source)
        self.assertIn("/v1/entity-aliases/runtime/confirm-batch", page_source)
        self.assertIn("reviewEntityAliasCandidate", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/review", page_source)
        self.assertIn("reviewEntityAliasCandidatesBatch", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/review-batch", page_source)
        self.assertIn("assignEntityAliasCandidateReview", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assign", page_source)
        self.assertIn("actionEntityAliasCandidateAssignment", page_source)
        self.assertIn("entityAliasAssignmentAction", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-action", page_source)
        self.assertIn("Claim review", page_source)
        self.assertIn("Release review", page_source)
        self.assertIn("entity_alias_candidate_assignment_actioned", page_source)
        self.assertIn("actionEntityAliasCandidateAssignmentsBatch", page_source)
        self.assertIn("entityAliasAssignmentBatchAction", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-actions", page_source)
        self.assertIn("Claim workbench records", page_source)
        self.assertIn("Release workbench records", page_source)
        self.assertIn("entity_alias_candidate_assignment_batch_actioned", page_source)
        self.assertIn("Alias Candidate Review History", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/reviews", page_source)
        self.assertIn("entityAliasCandidateReviews", page_source)
        self.assertIn("Alias Candidate Assignment Queue", page_source)
        self.assertIn("entityAliasAssignmentQueue", page_source)
        self.assertIn("entityAliasAssignmentStats", page_source)
        self.assertIn("Alias Reviewer Workbench", page_source)
        self.assertIn("entityAliasAssignmentWorkbench", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-workbench", page_source)
        self.assertIn("entity_alias_assignment_workbench_v1", page_source)
        self.assertIn("Alias Reviewer Workload", page_source)
        self.assertIn("entityAliasAssignmentWorkload", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-workload", page_source)
        self.assertIn("entity_alias_assignment_workload_v1", page_source)
        self.assertIn("reviewer_loads", page_source)
        self.assertIn("Alias Assignment Dispatch Plan", page_source)
        self.assertIn("entityAliasAssignmentDispatchPlan", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-dispatch-plan", page_source)
        self.assertIn("entity_alias_assignment_dispatch_plan_v1", page_source)
        self.assertIn("proposed_assignments", page_source)
        self.assertIn("entityAliasAssignmentDispatchApply", page_source)
        self.assertIn("applyEntityAliasAssignmentDispatchPlan", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-dispatch-apply", page_source)
        self.assertIn("Apply dispatch plan", page_source)
        self.assertIn("entity_alias_assignment_dispatch_plan_applied", page_source)
        self.assertIn("entity_alias_candidate_assignment_dispatch_applied", page_source)
        self.assertIn("Alias Assignment Queue Stats", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-stats", page_source)
        self.assertIn("entityAliasAssignmentNotifications", page_source)
        self.assertIn("enqueueEntityAliasAssignmentNotifications", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-notifications", page_source)
        self.assertIn("Queue overdue assignment notifications", page_source)
        self.assertIn("entityAliasAssignmentEscalations", page_source)
        self.assertIn("escalateEntityAliasAssignmentReviews", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-escalations", page_source)
        self.assertIn("Escalate overdue assignments", page_source)
        self.assertIn("entityAliasAssignmentReassignments", page_source)
        self.assertIn("reassignEntityAliasAssignmentReviews", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-reassignments", page_source)
        self.assertIn("Reassign escalated reviews", page_source)
        self.assertIn("entity_alias_assignment_overdue", page_source)
        self.assertIn("entity_alias_candidate_assignment_escalated", page_source)
        self.assertIn("entity_alias_candidate_assignment_reassigned", page_source)
        self.assertIn("entity_alias_assignment_queue_stats_v1", page_source)
        self.assertIn("overdue_count", page_source)
        self.assertIn("due_soon_count", page_source)
        self.assertIn("active statuses", page_source)
        self.assertIn("status_counts", page_source)
        self.assertIn("priority_counts", page_source)
        self.assertIn("aliasAssignmentStats", page_source)
        self.assertIn('assignment_status: "assigned"', page_source)
        self.assertIn("assigned_to /", page_source)
        self.assertIn("due_before filters", page_source)
        self.assertIn("Start review", page_source)
        self.assertIn("Block review", page_source)
        self.assertIn("Complete review", page_source)
        self.assertIn("Alias candidate assignment status changed to", page_source)
        self.assertIn('["in_progress", "blocked", "completed"]', page_source)
        self.assertIn("Assign review", page_source)
        self.assertIn('name="assigned_to"', page_source)
        self.assertIn('name="assignment_status"', page_source)
        self.assertIn('name="priority"', page_source)
        self.assertIn('name="due_at"', page_source)
        self.assertIn("Restore to needs review", page_source)
        self.assertIn("Mark approved", page_source)
        self.assertIn("Restore rejected alias candidate from review history", page_source)
        self.assertIn("entity_alias_candidate_review_batch_v1", page_source)
        self.assertIn("entity_alias_candidate_batch_reviewed", page_source)
        self.assertIn("Reject visible candidates", page_source)
        self.assertIn("Mark visible needs review", page_source)
        self.assertIn("Reject candidate", page_source)
        self.assertIn("Needs review", page_source)
        self.assertIn("latest_review", page_source)
        self.assertIn("entity_alias_confirm_batch_v1", page_source)
        self.assertIn("entity_alias_batch_confirmed", page_source)
        self.assertIn("entity_alias_confirmed audit event per alias", page_source)
        self.assertIn('name="candidate"', page_source)
        self.assertIn('name="candidate_review"', page_source)
        self.assertIn(".aliasBatchActions", css_source)
        self.assertIn("evidence_count", page_source)
        self.assertIn("evidence rows", page_source)
        self.assertIn("evidence_answer_run_ids", page_source)
        self.assertIn("Confirm visible candidates", page_source)
        self.assertIn(".aliasBatchQueue", css_source)

    def test_runtime_console_surfaces_manual_backfill_csv_import(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Manual Backfill CSV", page_source)
        self.assertIn("importManualBackfillCsv", page_source)
        self.assertIn("/v1/evidence-runs/runtime/manual-backfill/import.csv", page_source)
        self.assertIn("manual_backfill_csv_import_v1", page_source)
        self.assertIn("Import backfill CSV", page_source)
        self.assertIn('name="max_rows"', page_source)
        self.assertIn("Batch manual backfill import for auditable Google spike coverage", page_source)
        self.assertIn(".manualBackfillForm", css_source)

    def test_runtime_console_surfaces_pgvector_knowledge_search(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("pgvector Knowledge Search", page_source)
        self.assertIn("/v1/knowledge-facts/runtime/search", page_source)
        self.assertIn("RuntimeKnowledgeSearch", page_source)
        self.assertIn("knowledge_fact_embeddings_indexed", page_source)
        self.assertIn("fixture-knowledge-embedding-v1", page_source)

    def test_runtime_console_surfaces_content_engine_export(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Content Engine Detail", page_source)
        self.assertIn('content: "/v1/content-engines/runtime"', page_source)
        self.assertIn('contentExport: "/v1/content-engines/runtime/export.csv"', page_source)
        self.assertIn("contentEnginesExportUrl", page_source)
        self.assertIn("Content query", page_source)
        self.assertIn("Content CSV", page_source)
        self.assertIn("Download content CSV", page_source)

    def test_runtime_console_surfaces_traceability_export(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Traceability Detail", page_source)
        self.assertIn('traceability: "/v1/traceability/runtime"', page_source)
        self.assertIn('traceabilityExport: "/v1/traceability/runtime/export.csv"', page_source)
        self.assertIn("traceabilityExportUrl", page_source)
        self.assertIn("Traceability query", page_source)
        self.assertIn("Traceability CSV", page_source)
        self.assertIn("Download traceability CSV", page_source)


if __name__ == "__main__":
    unittest.main()
