from __future__ import annotations

from pathlib import Path
import unittest


class WebConsoleContractsTest(unittest.TestCase):
    def test_runtime_console_contains_traceability_links_and_graph_maps(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        traceability_source = Path("apps/web/app/traceability/page.tsx").read_text(encoding="utf-8")

        self.assertIn("function CitationGraphMap", page_source)
        self.assertIn("function TraceabilityMap", page_source)
        self.assertIn("function NodeLink", page_source)
        self.assertIn('id={anchorId("traceability-map", "runtime")}', page_source)
        self.assertIn('id={anchorId("source-node", item.node.id)}', page_source)
        self.assertIn('id={anchorId("answer-run", run.answer_run.id)}', page_source)
        self.assertIn('href={anchorHref("answer-run", run.answer_run.id)}', page_source)
        self.assertIn('href={anchorHref("source-node", item.node.id)}', page_source)
        self.assertIn("Open traceability detail", page_source)
        self.assertIn("/traceability", page_source)
        self.assertIn("Standalone runtime traceability map", traceability_source)
        self.assertIn('traceability: "/v1/traceability/runtime"', traceability_source)
        self.assertIn('graphs: "/v1/citation-graphs/runtime"', traceability_source)
        self.assertIn('projects: "/v1/projects/runtime"', traceability_source)
        self.assertIn("runtimePath(endpoints.traceability", traceability_source)
        self.assertIn('fixtureTraceability: "/v1/traceability/au/p0a-fixture"', traceability_source)
        self.assertIn('fixtureGraph: "/v1/citation-graphs/au/p0a-fixture"', traceability_source)
        self.assertIn("Fixture fallback", traceability_source)
        self.assertIn("normalizeFixtureTraceability", traceability_source)
        self.assertIn("normalizeFixtureGraph", traceability_source)
        self.assertIn("project_id", traceability_source)
        self.assertIn('id={anchorId("answer-run", run.answer_run.id)}', traceability_source)
        self.assertIn('id={anchorId("source-node", item.node.id)}', traceability_source)
        self.assertIn('id={anchorId("action", action.id || action.title)}', traceability_source)
        self.assertIn('id={anchorId("content-draft", item.draft.id || item.draft.title)}', traceability_source)
        self.assertIn('href={anchorHref(node.kind, node.value)}', traceability_source)
        self.assertIn("Back to console", traceability_source)

    def test_runtime_console_styles_highlight_deep_link_targets(self) -> None:
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn(".graphCanvas", css_source)
        self.assertIn(".traceMapCanvas", css_source)
        self.assertIn(".nodeLink", css_source)
        self.assertIn(".traceabilityPage", css_source)
        self.assertIn(".traceabilityTwoColumn", css_source)
        self.assertIn(".traceabilityStandaloneMap", css_source)
        self.assertIn(".noticeMini", css_source)
        self.assertIn(":target", css_source)

    def test_runtime_console_discloses_report_method_boundaries(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Method Disclosure", page_source)
        self.assertIn("Google coverage", page_source)
        self.assertIn("Google gate", page_source)
        self.assertIn("API/browser fidelity", page_source)
        self.assertIn("Trigger denominator", page_source)
        self.assertIn("Mention denominator", page_source)
        self.assertIn("Recommendation denominator", page_source)
        self.assertIn("Attempted records", page_source)
        self.assertIn("Surface-triggered records", page_source)
        self.assertIn("Evidence trigger rate", page_source)
        self.assertIn("score_rate_denominators", page_source)
        self.assertIn("Access distribution", page_source)
        self.assertIn("Google remains outside the main scoring denominator", page_source)

    def test_runtime_console_surfaces_api_browser_fidelity_checks(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn('fidelityChecks: "/v1/fidelity-checks/runtime"', page_source)
        self.assertIn('fidelityTrend: "/v1/fidelity-checks/runtime/trend"', page_source)
        self.assertIn("RuntimeFidelityCheck", page_source)
        self.assertIn("RuntimeFidelityTrend", page_source)
        self.assertIn("api_browser_fidelity_checked", page_source)
        self.assertIn("Fidelity audit", page_source)
        self.assertIn("Fidelity query", page_source)
        self.assertIn("Fidelity trend", page_source)
        self.assertIn("Trend query", page_source)
        self.assertIn("Payload hash", page_source)

    def test_runtime_console_surfaces_au_launch_status_gate(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn('launchStatus: "/v1/launch-status/au"', page_source)
        self.assertIn('launchRemediationPlan: "/v1/launch-remediation-plan/au"', page_source)
        self.assertIn('p0aEnvironmentChecklist: "/v1/p0a-environment-checklist/au"', page_source)
        self.assertIn('p0aExecutionChecklist: "/v1/p0a-execution-checklist/au"', page_source)
        self.assertIn('p0bGoogleExecutionChecklist: "/v1/p0b-google-execution-checklist/au"', page_source)
        self.assertIn('broaderPlatformRegistry: "/v1/au-broader-platform-registry"', page_source)
        self.assertIn('retestSchedulerPlan: "/v1/au-retest-scheduler-plan"', page_source)
        self.assertIn('retestExecutionStatus: "/v1/au-retest-execution-status"', page_source)
        self.assertIn('handoffDossier: "/v1/handoff-dossier/au"', page_source)
        self.assertIn("type AuLaunchStatus", page_source)
        self.assertIn("type AuLaunchRemediationPlan", page_source)
        self.assertIn("type AuP0aEnvironmentChecklist", page_source)
        self.assertIn("type AuP0aExecutionChecklist", page_source)
        self.assertIn("type AuP0bGoogleExecutionChecklist", page_source)
        self.assertIn("type AuBroaderPlatformRegistry", page_source)
        self.assertIn("type AuRetestSchedulerPlan", page_source)
        self.assertIn("type AuRetestExecutionStatus", page_source)
        self.assertIn("type AuHandoffDossier", page_source)
        self.assertIn("AU Launch Gate", page_source)
        self.assertIn("ready_for_customer_report_handoff", page_source)
        self.assertIn("launch_status_hash", page_source)
        self.assertIn("remediation_plan_hash", page_source)
        self.assertIn("handoff_dossier_hash", page_source)
        self.assertIn("Handoff dossier", page_source)
        self.assertIn("handoff_posture", page_source)
        self.assertIn("scripts/verify_au_handoff_dossier.py --require-customer-ready", page_source)
        self.assertIn("Execution status", page_source)
        self.assertIn("Execution ready", page_source)
        self.assertIn("Comparison allowed", page_source)
        self.assertIn("Missing artifacts", page_source)
        self.assertIn("Status hash", page_source)
        self.assertIn("retestExecutionGrid", css_source)
        self.assertIn("retestExecutionWindow", css_source)
        self.assertIn("Remediation plan", page_source)
        self.assertIn("P0a environment checklist", page_source)
        self.assertIn("P0a execution checklist", page_source)
        self.assertIn("p0a_execution_checklist_hash", page_source)
        self.assertIn("paths.p0aExecutionChecklist", page_source)
        self.assertIn("python3 scripts/verify_au_p0a_status_report.py --require-design-partner-ready", page_source)
        self.assertIn("P0b Google execution checklist", page_source)
        self.assertIn("google_execution_checklist_hash", page_source)
        self.assertIn("missing_selector_groups", page_source)
        self.assertIn("paths.p0bGoogleExecutionChecklist", page_source)
        self.assertIn("python3 scripts/verify_au_p0b_google_evidence_package.py --require-google-main-scoring-allowed", page_source)
        self.assertIn("Broader platform registry", page_source)
        self.assertIn("broader_platform_registry_hash", page_source)
        self.assertIn("gemini_search", page_source)
        self.assertIn("productreview_reviews", page_source)
        self.assertIn("paths.broaderPlatformRegistry", page_source)
        self.assertIn("AU Retest Scheduler Plan", page_source)
        self.assertIn("retest_scheduler_plan_hash", page_source)
        self.assertIn("planned_not_temporalized", page_source)
        self.assertIn("paths.retestSchedulerPlan", page_source)
        self.assertIn("environment_checklist_hash", page_source)
        self.assertIn("missing_required", page_source)
        self.assertIn("paths.p0aEnvironmentChecklist", page_source)
        self.assertIn("python3 scripts/verify_au_p0a_env_report.py --require-ready-environment", page_source)
        self.assertIn("next_work_item_id", page_source)
        self.assertIn("blocker_remediations", page_source)
        self.assertIn("p0a_design_partner", page_source)
        self.assertIn("p0b_google", page_source)
        self.assertIn("p0c_customer_report", page_source)
        self.assertIn("Remaining blockers", page_source)
        self.assertIn("Next action", page_source)
        self.assertIn("paths.launchStatus", page_source)
        self.assertIn("paths.launchRemediationPlan", page_source)
        self.assertIn("paths.handoffDossier", page_source)
        self.assertIn(".launchStatusPanel", css_source)
        self.assertIn(".launchStatusHeader", css_source)
        self.assertIn(".launchStageGrid", css_source)
        self.assertIn(".launchEvidenceGrid", css_source)
        self.assertIn(".launchBlockers", css_source)
        self.assertIn(".launchRemediation", css_source)
        self.assertIn(".p0aEnvironmentChecklist", css_source)
        self.assertIn(".p0bGoogleExecutionChecklist", css_source)
        self.assertIn(".broaderPlatformRegistry", css_source)
        self.assertIn(".retestSchedulerPlan", css_source)
        self.assertIn(".retestTimeline", css_source)
        self.assertIn(".retestWindow", css_source)
        self.assertIn(".platformRegistryGrid", css_source)
        self.assertIn(".platformCandidate", css_source)
        self.assertIn(".environmentChecklistGrid", css_source)
        self.assertIn(".handoffDossier", css_source)
        self.assertIn(".handoffBoundary", css_source)
        self.assertIn(".remediationList", css_source)
        self.assertIn(".remediationItem", css_source)

    def test_runtime_console_surfaces_collection_run_quality(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn('collectionRuns: "/v1/collection-runs/runtime"', page_source)
        self.assertIn("type CollectionRun", page_source)
        self.assertIn("Collection Run Quality", page_source)
        self.assertIn("Success rate", page_source)
        self.assertIn("Trigger rate", page_source)
        self.assertIn("Answer rate", page_source)
        self.assertIn("Total cost", page_source)
        self.assertIn("Avg cost/run", page_source)
        self.assertIn("Avg duration", page_source)
        self.assertIn("Duration", page_source)
        self.assertIn("duration_ms", page_source)
        self.assertIn("total_duration_ms", page_source)
        self.assertIn("average_duration_ms", page_source)
        self.assertIn("failure_summary", page_source)

    def test_runtime_console_surfaces_parser_comparison(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Parser agreement", page_source)
        self.assertIn("parser_comparison", page_source)
        self.assertIn("parser_ab_compare_v1", page_source)
        self.assertIn("parserComparisonText", page_source)
        self.assertIn("mismatches", page_source)
        self.assertIn("llm_call_log", page_source)
        self.assertIn("LLM call", page_source)

    def test_runtime_console_surfaces_score_weight_configuration(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Score Weights", page_source)
        self.assertIn("saveScoreWeightConfig", page_source)
        self.assertIn("/v1/score-weight-configs/runtime", page_source)
        self.assertIn("/v1/score-formulas/runtime", page_source)
        self.assertIn("Formula catalog", page_source)
        self.assertIn("Formula version", page_source)
        self.assertIn("Selected formula", page_source)
        self.assertIn("Formula status", page_source)
        self.assertIn("Formula note", page_source)
        self.assertIn("Supersedes", page_source)
        self.assertIn("component_weights_snapshot", page_source)
        self.assertIn("Weight snapshot", page_source)

    def test_runtime_console_surfaces_brand_logo_upload(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Logo Upload", page_source)
        self.assertIn("uploadProjectBrandLogo", page_source)
        self.assertIn("/v1/project-brand-kits/runtime/logo", page_source)
        self.assertIn('name="brand_logo"', page_source)
        self.assertIn('type="file"', page_source)
        self.assertIn("project_brand_logo_uploaded", page_source)
        self.assertIn("Theme Editor", page_source)
        self.assertIn("themeEditorPreview", page_source)
        self.assertIn("advanced white-label theme editor", page_source)
        self.assertIn("Template payload", page_source)
        self.assertIn('type="color"', page_source)
        self.assertIn("primary_color", page_source)
        self.assertIn("secondary_color", page_source)
        self.assertIn("project_brand_kit_saved", page_source)
        self.assertIn("Brand Assets", page_source)
        self.assertIn("RuntimeProjectBrandAssetVersion", page_source)
        self.assertIn("RuntimeProjectBrandAsset", page_source)
        self.assertIn("activateProjectBrandAssetVersion", page_source)
        self.assertIn("saveProjectBrandAsset", page_source)
        self.assertIn("updateProjectBrandAssetScanStatus", page_source)
        self.assertIn("/v1/project-brand-kits/runtime/assets", page_source)
        self.assertIn("/v1/project-brand-kits/runtime/assets/activate", page_source)
        self.assertIn("/v1/project-brand-assets/runtime", page_source)
        self.assertIn("/v1/project-brand-assets/runtime/${assetId}/scan-status", page_source)
        self.assertIn('name="asset_url"', page_source)
        self.assertIn('name="preview_url"', page_source)
        self.assertIn('name="scan_status"', page_source)
        self.assertIn("project_brand_asset_scan_recorded", page_source)
        self.assertIn("Asset Register", page_source)
        self.assertIn("Asset Library", page_source)
        self.assertIn("project_brand_asset_library_v1", page_source)
        self.assertIn("project_brand_assets", page_source)
        self.assertIn("Preview asset", page_source)
        self.assertIn(".themeEditorPreview", css_source)
        self.assertIn(".themePreviewCard", css_source)
        self.assertIn(".themeMetricStrip", css_source)
        self.assertIn(".themeColorField", css_source)
        self.assertIn(".brandAssetLibrary", css_source)
        self.assertIn(".brandAssetForm", css_source)
        self.assertIn(".assetActivateForm", css_source)
        self.assertIn(".inlineLink", css_source)

    def test_runtime_console_surfaces_report_history_management(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Report History", page_source)
        self.assertIn("recordRuntimeReportManagementEvent", page_source)
        self.assertIn("/v1/reports/runtime/${reportExportId}/management-events", page_source)
        self.assertIn("report_export_management_recorded", page_source)
        self.assertIn('name="report_export_id"', page_source)
        self.assertIn('name="status"', page_source)
        self.assertIn("client_ready", page_source)
        self.assertIn("Record status", page_source)
        self.assertIn("reportArtifactSignedUrlPath", page_source)
        self.assertIn("/signed-url", page_source)
        self.assertIn("Signed PDF URL", page_source)
        self.assertIn("Signed white-label URL", page_source)
        self.assertIn("HMAC signed URL endpoint", page_source)
        self.assertIn("Report Export Queue", page_source)
        self.assertIn("enqueueRuntimeReportExportJob", page_source)
        self.assertIn("updateRuntimeReportExportJobStatus", page_source)
        self.assertIn("/v1/report-export-jobs/runtime", page_source)
        self.assertIn("/v1/report-export-jobs/runtime/stats", page_source)
        self.assertIn("/v1/report-export-jobs/runtime/${jobId}/status", page_source)
        self.assertIn("report_export_job_queued", page_source)
        self.assertIn("report_export_job_status_updated", page_source)
        self.assertIn("RuntimeReportExportJobQueueStats", page_source)
        self.assertIn("Runtime Notifications", page_source)
        self.assertIn("RuntimeNotificationPage", page_source)
        self.assertIn("RuntimeNotificationSubscription", page_source)
        self.assertIn("RuntimeNotificationDelivery", page_source)
        self.assertIn("saveRuntimeNotificationSubscription", page_source)
        self.assertIn("updateRuntimeNotificationStatus", page_source)
        self.assertIn("/v1/runtime-notifications", page_source)
        self.assertIn("/v1/runtime-notification-subscriptions", page_source)
        self.assertIn("/v1/runtime-notification-deliveries", page_source)
        self.assertIn("/v1/runtime-notifications/${notificationId}/status", page_source)
        self.assertIn("runtime_notification_created", page_source)
        self.assertIn("runtime_notification_v1", page_source)
        self.assertIn("runtime_notification_subscription_saved", page_source)
        self.assertIn("runtime_notification_delivery_status_updated", page_source)
        self.assertIn("notificationSubscriptions", page_source)
        self.assertIn("notificationDeliveries", page_source)
        self.assertIn("Save subscription", page_source)
        self.assertIn('name="channel"', page_source)
        self.assertIn('value="slack"', page_source)
        self.assertIn('value="email"', page_source)
        self.assertIn("Slack Incoming Webhook URL", page_source)
        self.assertIn("mailto:ops@example.com", page_source)
        self.assertIn("slack_channel", page_source)
        self.assertIn("email_reply_to", page_source)
        self.assertIn("runtime_alert", page_source)
        self.assertIn("signing_secret_env", page_source)
        self.assertIn("GENO_NOTIFICATION_WEBHOOK_SIGNING_SECRET", page_source)
        self.assertIn("unread_count", page_source)
        self.assertIn("retryable_count", page_source)
        self.assertIn("expired_running_count", page_source)
        self.assertIn("dead_letter", page_source)
        self.assertIn("attempt_count", page_source)
        self.assertIn("lease_expires_at", page_source)
        self.assertIn("next_attempt_at", page_source)
        self.assertIn("Queue export", page_source)
        self.assertIn("Update job", page_source)
        self.assertIn(".reportManagementForm", css_source)
        self.assertIn(".reportExportJobForm", css_source)
        self.assertIn(".queueStatsGrid", css_source)

    def test_runtime_console_surfaces_project_member_management(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Project Members", page_source)
        self.assertIn("RuntimeProjectMember", page_source)
        self.assertIn("RuntimeProjectMemberInvitation", page_source)
        self.assertIn("saveRuntimeProjectMember", page_source)
        self.assertIn("deleteRuntimeProjectMember", page_source)
        self.assertIn("createRuntimeProjectMemberInvitation", page_source)
        self.assertIn("actionRuntimeProjectMemberInvitation", page_source)
        self.assertIn("emailRuntimeProjectMemberInvitation", page_source)
        self.assertIn("acceptRuntimeProjectMemberInvitation", page_source)
        self.assertIn("/v1/project-members/runtime", page_source)
        self.assertIn("/v1/project-member-invitations/runtime", page_source)
        self.assertIn("/v1/project-member-invitations/runtime/action", page_source)
        self.assertIn("/v1/project-member-invitations/runtime/email", page_source)
        self.assertIn("/v1/project-member-invitations/runtime/accept", page_source)
        self.assertIn('method: "DELETE"', page_source)
        self.assertIn("project_member_saved", page_source)
        self.assertIn("project_member_deleted", page_source)
        self.assertIn("project_member_invitation_created", page_source)
        self.assertIn("project_member_invitation_email_sent", page_source)
        self.assertIn("project_member_invitation_accepted", page_source)
        self.assertIn("project_member_invitation_revoked", page_source)
        self.assertIn("project_member_invitation_expired", page_source)
        self.assertIn("Email invite", page_source)
        self.assertIn("Accept invite", page_source)
        self.assertIn("Revoke invite", page_source)
        self.assertIn("Expire invite", page_source)
        self.assertIn('name="user_id"', page_source)
        self.assertIn('name="invitation_id"', page_source)
        self.assertIn('name="email"', page_source)
        self.assertIn('name="role"', page_source)
        self.assertIn("project_members gate", page_source)
        self.assertIn(".projectMemberForm", css_source)
        self.assertIn(".projectMemberDeleteForm", css_source)
        self.assertIn(".inlineActions", css_source)
        self.assertIn(".inlineForm", css_source)

    def test_invite_accept_page_exchanges_token_without_login_assumption(self) -> None:
        page_source = Path("apps/web/app/invite/accept/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("InviteAcceptPage", page_source)
        self.assertIn("acceptProjectInvitation", page_source)
        self.assertIn("GENO_WEB_INVITE_ACCEPT_AUTO_SUBMIT", page_source)
        self.assertIn("/v1/project-member-invitations/runtime/accept", page_source)
        self.assertIn('name="invitation_id"', page_source)
        self.assertIn('name="invite_token"', page_source)
        self.assertIn("project_member_invitation_accepted", page_source)
        self.assertIn("Accept invitation", page_source)
        self.assertIn(".inviteShell", css_source)
        self.assertIn(".inviteAcceptForm", css_source)
        self.assertIn(".inviteResult", css_source)
        self.assertIn(".textButton", css_source)

    def test_runtime_console_surfaces_runtime_alerts(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Runtime Alerts", page_source)
        self.assertIn("RuntimeAlert", page_source)
        self.assertIn("/v1/runtime-alerts", page_source)
        self.assertIn("runtime_alerts_v1", page_source)
        self.assertIn("evidence_refs", page_source)
        self.assertIn("related_actions", page_source)
        self.assertIn("management_events", page_source)
        self.assertIn("recordRuntimeAlertEvent", page_source)
        self.assertIn("enqueueRuntimeAlertNotifications", page_source)
        self.assertIn("runtimeAlertEventPath", page_source)
        self.assertIn("/v1/runtime-alerts/${alertId}/events", page_source)
        self.assertIn("/v1/runtime-alerts/notifications", page_source)
        self.assertIn("Queue alert notifications", page_source)
        self.assertIn("Record alert event", page_source)
        self.assertIn('value="acknowledged"', page_source)
        self.assertIn('value="resolved"', page_source)
        self.assertIn('value="snoozed"', page_source)
        self.assertIn('value="reopened"', page_source)
        self.assertIn('value="escalated"', page_source)
        self.assertIn("Alert query", page_source)
        self.assertIn(".alertGrid", css_source)
        self.assertIn(".alertItem", css_source)
        self.assertIn(".inlineForm", css_source)

    def test_runtime_console_surfaces_prompt_file_import(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("Prompt CSV Import", page_source)
        self.assertIn("Prompt File Import", page_source)
        self.assertIn("importRuntimePromptsFile", page_source)
        self.assertIn("/v1/prompts/runtime/import.csv", page_source)
        self.assertIn("/v1/prompts/runtime/import.file", page_source)
        self.assertIn("/v1/prompts/runtime/imports", page_source)
        self.assertIn("RuntimePromptImportHistoryItem", page_source)
        self.assertIn("Prompt Import History", page_source)
        self.assertIn("Import query", page_source)
        self.assertIn(".csv or .xlsx", page_source)
        self.assertIn('name="prompt_file"', page_source)

    def test_runtime_console_surfaces_question_detail_matrix(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Question Detail", page_source)
        self.assertIn("questionEvidence", page_source)
        self.assertIn("buildQuestionDetailRows", page_source)
        self.assertIn("Question coverage", page_source)
        self.assertIn("Question evidence query", page_source)
        self.assertIn("Missing platforms", page_source)
        self.assertIn(".questionTable", css_source)
        self.assertIn(".questionRow", css_source)
        self.assertIn(".coverageBadge", css_source)
        self.assertIn(".coverage-platform_gap", css_source)

    def test_runtime_console_surfaces_human_review_trail(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Human Review Trail", page_source)
        self.assertIn("Review Queue", page_source)
        self.assertIn("submitHumanReview", page_source)
        self.assertIn("/v1/human-reviews/runtime", page_source)
        self.assertIn("/v1/human-reviews/runtime/queue", page_source)
        self.assertIn("RuntimeHumanReviewQueueItem", page_source)
        self.assertIn("Queue query", page_source)
        self.assertIn("human_review_recorded", page_source)
        self.assertIn("content_draft_review_status_updated", page_source)
        self.assertIn("Draft audit", page_source)
        self.assertIn("human_review_v1", page_source)
        self.assertIn("approved_for_report", page_source)
        self.assertIn(".humanReviewGrid", css_source)
        self.assertIn(".humanReviewForm", css_source)

    def test_runtime_console_surfaces_entity_alias_batch_review_queue(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Bulk Alias Review Queue", page_source)
        self.assertIn("confirmEntityAliasBatch", page_source)
        self.assertIn("/v1/entity-aliases/runtime/confirm-batch", page_source)
        self.assertIn("reviewEntityAliasCandidate", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/review", page_source)
        self.assertIn("reviewEntityAliasCandidatesBatch", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/review-batch", page_source)
        self.assertIn("assignEntityAliasCandidateReview", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assign", page_source)
        self.assertIn("actionEntityAliasCandidateAssignment", page_source)
        self.assertIn("entityAliasAssignmentAction", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-action", page_source)
        self.assertIn("Claim review", page_source)
        self.assertIn("Release review", page_source)
        self.assertIn("entity_alias_candidate_assignment_actioned", page_source)
        self.assertIn("Alias Candidate Review History", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/reviews", page_source)
        self.assertIn("entityAliasCandidateReviews", page_source)
        self.assertIn("Alias Candidate Assignment Queue", page_source)
        self.assertIn("entityAliasAssignmentQueue", page_source)
        self.assertIn("entityAliasAssignmentStats", page_source)
        self.assertIn("Alias Assignment Queue Stats", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-stats", page_source)
        self.assertIn("entityAliasAssignmentNotifications", page_source)
        self.assertIn("enqueueEntityAliasAssignmentNotifications", page_source)
        self.assertIn("/v1/entity-aliases/runtime/candidates/assignment-notifications", page_source)
        self.assertIn("Queue overdue assignment notifications", page_source)
        self.assertIn("entity_alias_assignment_overdue", page_source)
        self.assertIn("entity_alias_assignment_queue_stats_v1", page_source)
        self.assertIn("overdue_count", page_source)
        self.assertIn("due_soon_count", page_source)
        self.assertIn("status_counts", page_source)
        self.assertIn("priority_counts", page_source)
        self.assertIn("aliasAssignmentStats", page_source)
        self.assertIn('assignment_status: "assigned"', page_source)
        self.assertIn("assigned_to /", page_source)
        self.assertIn("due_before filters", page_source)
        self.assertIn("Start review", page_source)
        self.assertIn("Block review", page_source)
        self.assertIn("Complete review", page_source)
        self.assertIn("Alias candidate assignment status changed to", page_source)
        self.assertIn('["in_progress", "blocked", "completed"]', page_source)
        self.assertIn("Assign review", page_source)
        self.assertIn('name="assigned_to"', page_source)
        self.assertIn('name="assignment_status"', page_source)
        self.assertIn('name="priority"', page_source)
        self.assertIn('name="due_at"', page_source)
        self.assertIn("Restore to needs review", page_source)
        self.assertIn("Mark approved", page_source)
        self.assertIn("Restore rejected alias candidate from review history", page_source)
        self.assertIn("entity_alias_candidate_review_batch_v1", page_source)
        self.assertIn("entity_alias_candidate_batch_reviewed", page_source)
        self.assertIn("Reject visible candidates", page_source)
        self.assertIn("Mark visible needs review", page_source)
        self.assertIn("Reject candidate", page_source)
        self.assertIn("Needs review", page_source)
        self.assertIn("latest_review", page_source)
        self.assertIn("entity_alias_confirm_batch_v1", page_source)
        self.assertIn("entity_alias_batch_confirmed", page_source)
        self.assertIn("entity_alias_confirmed audit event per alias", page_source)
        self.assertIn('name="candidate"', page_source)
        self.assertIn('name="candidate_review"', page_source)
        self.assertIn(".aliasBatchActions", css_source)
        self.assertIn("evidence_count", page_source)
        self.assertIn("evidence rows", page_source)
        self.assertIn("evidence_answer_run_ids", page_source)
        self.assertIn("Confirm visible candidates", page_source)
        self.assertIn(".aliasBatchQueue", css_source)

    def test_runtime_console_surfaces_manual_backfill_csv_import(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")
        css_source = Path("apps/web/app/globals.css").read_text(encoding="utf-8")

        self.assertIn("Manual Backfill CSV", page_source)
        self.assertIn("importManualBackfillCsv", page_source)
        self.assertIn("/v1/evidence-runs/runtime/manual-backfill/import.csv", page_source)
        self.assertIn("manual_backfill_csv_import_v1", page_source)
        self.assertIn("Import backfill CSV", page_source)
        self.assertIn('name="max_rows"', page_source)
        self.assertIn("Batch manual backfill import for auditable Google spike coverage", page_source)
        self.assertIn(".manualBackfillForm", css_source)

    def test_runtime_console_surfaces_pgvector_knowledge_search(self) -> None:
        page_source = Path("apps/web/app/page.tsx").read_text(encoding="utf-8")

        self.assertIn("pgvector Knowledge Search", page_source)
        self.assertIn("/v1/knowledge-facts/runtime/search", page_source)
        self.assertIn("RuntimeKnowledgeSearch", page_source)
        self.assertIn("knowledge_fact_embeddings_indexed", page_source)
        self.assertIn("fixture-knowledge-embedding-v1", page_source)


if __name__ == "__main__":
    unittest.main()
