from __future__ import annotations

from typing import Any, Protocol


class AccessControlRepository(Protocol):
    """Access/session/secret repository boundary for Production v1."""

    def set_runtime_project_access_context(self, *, actor_id: str, project_id: str | None = None) -> None: ...

    def set_runtime_project_invitation_accept_context(self, *, invite_token_hash: str) -> None: ...

    def set_runtime_project_portal_token_context(self, *, portal_token_hash: str) -> None: ...

    def user_can_access_project(self, *, project_id: str, actor_id: str) -> bool: ...

    def get_project_member_role(self, *, project_id: str, actor_id: str) -> str | None: ...

    def get_runtime_membership_scope(
        self,
        *,
        actor_id: str,
        tenant_id: str | None = None,
        project_id: str | None = None,
    ) -> Any: ...

    def create_runtime_session(self, session_input: Any) -> Any: ...

    def validate_runtime_session(self, raw_session_token: str) -> Any: ...

    def revoke_runtime_session(self, *, session_id: str, actor_id: str, reason: str = "") -> Any: ...

    def create_runtime_project_member_invitation(self, invitation: Any) -> Any: ...

    def accept_runtime_project_member_invitation(self, accept_input: Any) -> Any: ...

    def save_connector_secret(self, secret_input: Any) -> Any: ...

    def list_connector_secrets(self, *, project_id: str, provider: str | None = None) -> tuple[Any, ...]: ...

    def resolve_connector_secret(self, *, secret_ref: str) -> str: ...


__all__ = ["AccessControlRepository"]
