"""Stable contracts shared by production preflight validators."""

from __future__ import annotations

from dataclasses import dataclass


IMAGE_FIELDS = (
    "GEO_POSTGRES_IMAGE",
    "GEO_MINIO_IMAGE",
    "GEO_MINIO_MC_IMAGE",
    "GEO_VALKEY_IMAGE",
    "GEO_API_IMAGE",
    "GEO_ADMIN_WEB_IMAGE",
    "GEO_CUSTOMER_WEB_IMAGE",
    "GEO_OTEL_COLLECTOR_IMAGE",
    "GEO_STYLE_BROWSER_IMAGE",
)

SECRET_FILE_FIELDS = (
    "GEO_POSTGRES_INSTALLER_PASSWORD_FILE",
    "GEO_INSTALLER_DATABASE_URL_FILE",
    "GEO_DATABASE_URL_FILE",
    "GEO_WORKER_DATABASE_URL_FILE",
    "GEO_AUTH_TOKEN_SECRET_FILE",
    "GEO_MINIO_ROOT_USER_FILE",
    "GEO_MINIO_ROOT_PASSWORD_FILE",
    "GEO_OBJECT_STORE_ACCESS_KEY_FILE",
    "GEO_OBJECT_STORE_SECRET_KEY_FILE",
    "GEO_OBJECT_STORE_BACKUP_ACCESS_KEY_FILE",
    "GEO_OBJECT_STORE_BACKUP_SECRET_KEY_FILE",
    "GEO_OBJECT_STORE_RESTORE_ACCESS_KEY_FILE",
    "GEO_OBJECT_STORE_RESTORE_SECRET_KEY_FILE",
    "GEO_OBJECT_STORE_RETENTION_ACCESS_KEY_FILE",
    "GEO_OBJECT_STORE_RETENTION_SECRET_KEY_FILE",
    "GEO_DEEPSEEK_API_KEY_FILE",
    "GEO_RESTORE_SMOKE_PASSWORD_FILE",
    "GEO_SECRET_STORE_MASTER_KEYRING_FILE",
    "GEO_SECRET_STORE_REQUEST_HASH_KEY_FILE",
    "GEO_BACKUP_KEYRING_FILE",
    "GEO_PROVIDER_ARTIFACT_KEYRING_FILE",
    "GEO_SYNTHETIC_ARTIFACT_KEYRING_FILE",
    "GEO_RECOMMENDATION_ARTIFACT_KEYRING_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_KEYRING_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_OBJECT_STORE_ACCESS_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_OBJECT_STORE_SECRET_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_READER_ACCESS_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_READER_SECRET_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_DELETER_ACCESS_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_DELETER_SECRET_KEY_FILE",
    "GEO_STYLE_BROWSER_WORKER_DATABASE_URL_FILE",
    "GEO_SYNTHETIC_STYLE_ARTIFACT_WRITER_ACCESS_KEY_FILE",
    "GEO_SYNTHETIC_STYLE_ARTIFACT_WRITER_SECRET_KEY_FILE",
    "GEO_SYNTHETIC_ARTIFACT_DELETER_ACCESS_KEY_FILE",
    "GEO_SYNTHETIC_ARTIFACT_DELETER_SECRET_KEY_FILE",
    "GEO_ALERT_SMTP_USERNAME_FILE",
    "GEO_ALERT_SMTP_PASSWORD_FILE",
    "GEO_ALERT_WEBHOOK_SIGNING_SECRET_FILE",
)

CONFIG_FILE_FIELDS = ("GEO_STYLE_ADAPTER_REGISTRY_FILE",)

STRICT_0600_SECRET_FILE_FIELDS = frozenset(
    {
        "GEO_SECRET_STORE_MASTER_KEYRING_FILE",
        "GEO_SECRET_STORE_REQUEST_HASH_KEY_FILE",
        "GEO_BACKUP_KEYRING_FILE",
        "GEO_PROVIDER_ARTIFACT_KEYRING_FILE",
        "GEO_SYNTHETIC_ARTIFACT_KEYRING_FILE",
        "GEO_RECOMMENDATION_ARTIFACT_KEYRING_FILE",
        "GEO_WORKFLOW_C_ARTIFACT_KEYRING_FILE",
        "GEO_RESTORE_SMOKE_PASSWORD_FILE",
        "GEO_ALERT_SMTP_USERNAME_FILE",
        "GEO_ALERT_SMTP_PASSWORD_FILE",
        "GEO_ALERT_WEBHOOK_SIGNING_SECRET_FILE",
    }
)

HTTPS_URL_FIELDS = (
    "GEO_OIDC_DISCOVERY_URL",
    "GEO_JWT_ISSUER",
    "GEO_ADMIN_OIDC_LOGIN_URL",
    "GEO_ADMIN_OIDC_LOGOUT_URL",
    "GEO_ADMIN_WEB_BASE_URL",
    "GEO_CUSTOMER_WEB_BASE_URL",
    "GEO_ALERT_WEBHOOK_ENDPOINT",
)

REQUIRED_TEXT_FIELDS = (
    "GEO_JWT_AUDIENCE",
    "GEO_ADMIN_OIDC_ALLOWED_ORIGINS",
    "GEO_RELEASE_VERSION",
    "GEO_BACKUP_ROOT",
    "GEO_BACKUP_MINIO_STAGING_SIZE",
    "GEO_RESTORE_TMPFS_ROOT",
    "GEO_STYLE_COLLECTION_COMPOSITION_FACTORY",
    "GEO_STYLE_ALLOWED_EGRESS_HOSTS",
    "GEO_STYLE_CHROMIUM_EXECUTABLE",
    "GEO_STYLE_ADAPTER_REGISTRY_SHA256",
    "GEO_ALERT_SMTP_UPSTREAM_HOST",
    "GEO_ALERT_SMTP_UPSTREAM_ALLOWED_HOSTS",
    "GEO_ALERT_SMTP_TLS_MODE",
    "GEO_ALERT_SMTP_SENDER",
    "GEO_ALERT_SMTP_RECIPIENTS",
    "GEO_ALERT_WEBHOOK_ALLOWED_HOSTS",
    "GEO_MODEL_GATEWAY_WORKER_SERVICE_IDENTITY_ID",
    "GEO_STYLE_COLLECTION_SERVICE_IDENTITY_ID",
    "GEO_RESTORE_PROBE_SERVICE_IDENTITY_ID",
    "GEO_RESTORE_SECRET_REFERENCE_ID",
    "GEO_RESTORE_SECRET_PROJECT_ID",
    "GEO_RESTORE_SECRET_PURPOSE",
    "GEO_RESTORE_SECRET_VERSION",
    "GEO_RESTORE_SECRET_IDEMPOTENCY_KEY",
)

APPLICATION_SECRET_UID = 10001
APPLICATION_SECRET_GID = 10001
APPLICATION_SECRET_FILE_FIELDS = frozenset(
    {
        "GEO_SECRET_STORE_MASTER_KEYRING_FILE",
        "GEO_SECRET_STORE_REQUEST_HASH_KEY_FILE",
        "GEO_PROVIDER_ARTIFACT_KEYRING_FILE",
        "GEO_SYNTHETIC_ARTIFACT_KEYRING_FILE",
        "GEO_RECOMMENDATION_ARTIFACT_KEYRING_FILE",
        "GEO_WORKFLOW_C_ARTIFACT_KEYRING_FILE",
        "GEO_WORKFLOW_C_ARTIFACT_OBJECT_STORE_ACCESS_KEY_FILE",
        "GEO_WORKFLOW_C_ARTIFACT_OBJECT_STORE_SECRET_KEY_FILE",
        "GEO_WORKFLOW_C_ARTIFACT_READER_ACCESS_KEY_FILE",
        "GEO_WORKFLOW_C_ARTIFACT_READER_SECRET_KEY_FILE",
        "GEO_WORKFLOW_C_ARTIFACT_DELETER_ACCESS_KEY_FILE",
        "GEO_WORKFLOW_C_ARTIFACT_DELETER_SECRET_KEY_FILE",
        "GEO_RESTORE_SMOKE_PASSWORD_FILE",
        "GEO_STYLE_BROWSER_WORKER_DATABASE_URL_FILE",
        "GEO_SYNTHETIC_STYLE_ARTIFACT_WRITER_ACCESS_KEY_FILE",
        "GEO_SYNTHETIC_STYLE_ARTIFACT_WRITER_SECRET_KEY_FILE",
        "GEO_SYNTHETIC_ARTIFACT_DELETER_ACCESS_KEY_FILE",
        "GEO_SYNTHETIC_ARTIFACT_DELETER_SECRET_KEY_FILE",
        "GEO_ALERT_SMTP_USERNAME_FILE",
        "GEO_ALERT_SMTP_PASSWORD_FILE",
        "GEO_ALERT_WEBHOOK_SIGNING_SECRET_FILE",
    }
)

KEY_DOMAIN_FIELDS = (
    "GEO_BACKUP_KEYRING_FILE",
    "GEO_SECRET_STORE_MASTER_KEYRING_FILE",
    "GEO_SECRET_STORE_REQUEST_HASH_KEY_FILE",
    "GEO_PROVIDER_ARTIFACT_KEYRING_FILE",
    "GEO_SYNTHETIC_ARTIFACT_KEYRING_FILE",
    "GEO_RECOMMENDATION_ARTIFACT_KEYRING_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_KEYRING_FILE",
)
OBJECT_STORE_CREDENTIAL_FIELDS = (
    "GEO_MINIO_ROOT_USER_FILE",
    "GEO_MINIO_ROOT_PASSWORD_FILE",
    "GEO_OBJECT_STORE_ACCESS_KEY_FILE",
    "GEO_OBJECT_STORE_SECRET_KEY_FILE",
    "GEO_OBJECT_STORE_BACKUP_ACCESS_KEY_FILE",
    "GEO_OBJECT_STORE_BACKUP_SECRET_KEY_FILE",
    "GEO_OBJECT_STORE_RESTORE_ACCESS_KEY_FILE",
    "GEO_OBJECT_STORE_RESTORE_SECRET_KEY_FILE",
    "GEO_OBJECT_STORE_RETENTION_ACCESS_KEY_FILE",
    "GEO_OBJECT_STORE_RETENTION_SECRET_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_OBJECT_STORE_ACCESS_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_OBJECT_STORE_SECRET_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_READER_ACCESS_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_READER_SECRET_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_DELETER_ACCESS_KEY_FILE",
    "GEO_WORKFLOW_C_ARTIFACT_DELETER_SECRET_KEY_FILE",
    "GEO_SYNTHETIC_STYLE_ARTIFACT_WRITER_ACCESS_KEY_FILE",
    "GEO_SYNTHETIC_STYLE_ARTIFACT_WRITER_SECRET_KEY_FILE",
    "GEO_SYNTHETIC_ARTIFACT_DELETER_ACCESS_KEY_FILE",
    "GEO_SYNTHETIC_ARTIFACT_DELETER_SECRET_KEY_FILE",
)
ISOLATED_RECOVERY_SECRET_FIELDS = KEY_DOMAIN_FIELDS + OBJECT_STORE_CREDENTIAL_FIELDS + (
    "GEO_RESTORE_SMOKE_PASSWORD_FILE",
)

INTEGER_BOUNDS = {
    "GEO_READINESS_DEPENDENCY_TIMEOUT_SECONDS": (1, 10),
    "GEO_READINESS_TOTAL_TIMEOUT_SECONDS": (2, 30),
    "GEO_RUNTIME_HEARTBEAT_INTERVAL_SECONDS": (1, 300),
    "GEO_RUNTIME_HEARTBEAT_STALE_SECONDS": (1, 3_600),
    "GEO_RUNTIME_QUEUED_STALE_SECONDS": (1, 604_800),
    "GEO_RUNTIME_OUTBOX_STALE_SECONDS": (1, 604_800),
    "GEO_RUNTIME_RUNNING_GRACE_SECONDS": (0, 86_400),
    "GEO_RUNTIME_FAILURE_WINDOW_SECONDS": (1, 2_592_000),
    "GEO_RUNTIME_EXPECTED_TASK_WORKER_INSTANCES": (1, 100),
    "GEO_RUNTIME_EXPECTED_OUTBOX_RELAY_INSTANCES": (1, 100),
    "GEO_RUNTIME_EXPECTED_STYLE_BROWSER_WORKER_INSTANCES": (1, 1),
    "GEO_RUNTIME_EXPECTED_SYNTHETIC_ARTIFACT_MAINTENANCE_WORKER_INSTANCES": (1, 1),
    "GEO_SYNTHETIC_ARTIFACT_MAINTENANCE_POLL_SECONDS": (10, 3_600),
    "GEO_SYNTHETIC_ARTIFACT_MAINTENANCE_JOB_LEASE_SECONDS": (30, 3_600),
    "GEO_SYNTHETIC_ARTIFACT_EXPIRY_BATCH_SIZE": (1, 1_000),
    "GEO_SYNTHETIC_ARTIFACT_DELETION_LEASE_SECONDS": (5, 3_600),
    "GEO_SYNTHETIC_ARTIFACT_MAX_DELETIONS_PER_JOB": (1, 100),
    "GEO_RUNTIME_EXPECTED_WORKFLOW_C_MAINTENANCE_WORKER_INSTANCES": (1, 1),
    "GEO_WORKFLOW_C_ARTIFACT_MAINTENANCE_JOB_LEASE_SECONDS": (30, 3_600),
    "GEO_WORKFLOW_C_ARTIFACT_STAGED_GRACE_SECONDS": (60, 86_400),
    "GEO_WORKFLOW_C_ARTIFACT_DELETION_LEASE_SECONDS": (30, 3_600),
    "GEO_WORKFLOW_C_ARTIFACT_MAX_DELETIONS_PER_JOB": (1, 1_000),
    "GEO_RESTORE_SECRET_VERSION": (1, 2_147_483_647),
    "GEO_STYLE_ROBOTS_TIMEOUT_SECONDS": (10, 10),
    "GEO_ALERT_SMTP_UPSTREAM_PORT": (1, 65_535),
}


@dataclass(frozen=True, order=True)
class PreflightIssue:
    code: str
    field: str


__all__ = [
    "APPLICATION_SECRET_FILE_FIELDS",
    "APPLICATION_SECRET_GID",
    "APPLICATION_SECRET_UID",
    "CONFIG_FILE_FIELDS",
    "HTTPS_URL_FIELDS",
    "IMAGE_FIELDS",
    "INTEGER_BOUNDS",
    "ISOLATED_RECOVERY_SECRET_FIELDS",
    "KEY_DOMAIN_FIELDS",
    "OBJECT_STORE_CREDENTIAL_FIELDS",
    "PreflightIssue",
    "REQUIRED_TEXT_FIELDS",
    "SECRET_FILE_FIELDS",
    "STRICT_0600_SECRET_FILE_FIELDS",
]
