"""Core contracts and data models for the GENO AU evidence platform."""

from geno_core.action_plan import (
    build_action_plan_audit_event,
    build_action_recommendations,
    build_retest_schedule,
    build_retest_comparison_audit_event,
    compare_retest_windows,
)
from geno_core.analysis_pipeline import analyze_and_score_records, build_score_input_policy, select_score_input_records
from geno_core.bootstrap import build_au_project_bootstrap
from geno_core.collection import (
    CollectionExecutionPolicy,
    build_collection_run_audit_event,
    build_collection_run_summary,
    build_manual_backfill_record,
    build_p0a_collection_plan,
    collect_prompt_with_failure_record,
    evaluate_p0a_collection_readiness,
    run_collection_slice,
    run_fixture_collection_slice,
)
from geno_core.collectors import (
    FixtureChatGPTSearchBrowserCollector,
    FixtureGoogleAIModeCollector,
    FixtureGoogleAIOCollector,
    FixtureManualBackfillCollector,
    FixtureThirdPartySerpCollector,
    ManualBackfillCollector,
    OpenAIWebSearchCollector,
    PerplexitySonarCollector,
    PlaywrightChatGPTSearchCollector,
    PlaywrightAIModeCollector,
    PlaywrightGoogleAIOCollector,
    ThirdPartySerpCollector,
)
from geno_core.geo import StaticAUGeoProvider
from geno_core.google_spike import (
    build_google_spike_plan,
    evaluate_google_spike_gate,
    evaluate_google_spike_readiness_gate,
)
from geno_core.fidelity_schedule import build_browser_fidelity_sampling_plan
from geno_core.graph import build_citation_graph
from geno_core.industry import build_au_dtc_ecommerce_profile
from geno_core.knowledge import (
    build_content_drafts,
    build_content_engine_audit_event,
    build_integration_connectors,
    build_localized_knowledge_facts,
    build_manual_distribution_records,
    search_knowledge_facts,
)
from geno_core.llm_gateway import FixtureLLMGateway, LiteLLMGateway, LLMGatewayRetryExhaustedError
from geno_core.market import build_au_market_profile
from geno_core.prompt_pack import build_au_dtc_prompt_pack
from geno_core.report import MarkdownCsvReportExporter
from geno_core.repository import PostgresEvidenceRepository
from geno_core.runtime import (
    RuntimePersistenceError,
    RuntimeComponentDiagnostic,
    RuntimeDiagnostics,
    build_runtime_diagnostics,
    build_object_store_from_env,
    build_repository_from_env,
    close_runtime_postgres_pool,
    close_repository_connection,
    connect_postgres_from_env,
    runtime_database_diagnostic,
    runtime_object_store_diagnostic,
    runtime_auth_diagnostic,
)
from geno_core.object_store import archive_api_snapshot_assets, archive_browser_capture_assets, archive_project_brand_logo
from geno_core.scoring import (
    AU_VISIBILITY_V1,
    AU_VISIBILITY_V1_1_LOCAL_BOOST,
    RegistryScoringFormula,
    SCORE_FORMULA_REGISTRY,
    ScoreFormulaDefinition,
    get_score_formula,
    list_score_formulas,
    normalize_score_weights,
    rescore_snapshot_with_formula,
    score_answer_analyses,
    score_answer_analysis,
)
from geno_core.stubs import (
    NotConfiguredCollectorBackend,
    NotConfiguredParserEngine,
    NotConfiguredReportExporter,
    NotConfiguredScoringFormula,
)
from geno_core.traceability import build_traceability_bundle
from geno_core.webhook_signing import (
    RUNTIME_NOTIFICATION_WEBHOOK_SIGNATURE_KEY_ID_HEADER,
    RuntimeNotificationWebhookSignatureVerification,
    runtime_notification_webhook_payload_hash,
    sign_runtime_notification_webhook,
    verify_runtime_notification_webhook_signature,
)

__all__ = [
    "AU_VISIBILITY_V1",
    "AU_VISIBILITY_V1_1_LOCAL_BOOST",
    "SCORE_FORMULA_REGISTRY",
    "ScoreFormulaDefinition",
    "CollectionExecutionPolicy",
    "analyze_and_score_records",
    "build_score_input_policy",
    "select_score_input_records",
    "build_action_plan_audit_event",
    "build_action_recommendations",
    "build_au_dtc_ecommerce_profile",
    "build_au_dtc_prompt_pack",
    "build_au_market_profile",
    "build_au_project_bootstrap",
    "build_collection_run_audit_event",
    "build_collection_run_summary",
    "build_manual_backfill_record",
    "build_p0a_collection_plan",
    "build_retest_schedule",
    "build_traceability_bundle",
    "build_retest_comparison_audit_event",
    "collect_prompt_with_failure_record",
    "compare_retest_windows",
    "build_google_spike_plan",
    "build_browser_fidelity_sampling_plan",
    "build_object_store_from_env",
    "archive_api_snapshot_assets",
    "archive_browser_capture_assets",
    "archive_project_brand_logo",
    "build_citation_graph",
    "build_content_drafts",
    "build_content_engine_audit_event",
    "build_integration_connectors",
    "build_localized_knowledge_facts",
    "build_manual_distribution_records",
    "evaluate_google_spike_gate",
    "evaluate_google_spike_readiness_gate",
    "evaluate_p0a_collection_readiness",
    "get_score_formula",
    "build_repository_from_env",
    "close_runtime_postgres_pool",
    "close_repository_connection",
    "connect_postgres_from_env",
    "FixtureChatGPTSearchBrowserCollector",
    "FixtureGoogleAIModeCollector",
    "FixtureGoogleAIOCollector",
    "FixtureLLMGateway",
    "LiteLLMGateway",
    "LLMGatewayRetryExhaustedError",
    "FixtureManualBackfillCollector",
    "FixtureThirdPartySerpCollector",
    "ManualBackfillCollector",
    "MarkdownCsvReportExporter",
    "OpenAIWebSearchCollector",
    "PerplexitySonarCollector",
    "PlaywrightChatGPTSearchCollector",
    "PlaywrightAIModeCollector",
    "PlaywrightGoogleAIOCollector",
    "PostgresEvidenceRepository",
    "RuntimePersistenceError",
    "RuntimeNotificationWebhookSignatureVerification",
    "RuntimeComponentDiagnostic",
    "RuntimeDiagnostics",
    "build_runtime_diagnostics",
    "runtime_database_diagnostic",
    "runtime_object_store_diagnostic",
    "runtime_auth_diagnostic",
    "RegistryScoringFormula",
    "list_score_formulas",
    "normalize_score_weights",
    "NotConfiguredCollectorBackend",
    "NotConfiguredParserEngine",
    "NotConfiguredReportExporter",
    "NotConfiguredScoringFormula",
    "rescore_snapshot_with_formula",
    "run_collection_slice",
    "run_fixture_collection_slice",
    "score_answer_analyses",
    "score_answer_analysis",
    "search_knowledge_facts",
    "runtime_notification_webhook_payload_hash",
    "RUNTIME_NOTIFICATION_WEBHOOK_SIGNATURE_KEY_ID_HEADER",
    "sign_runtime_notification_webhook",
    "StaticAUGeoProvider",
    "ThirdPartySerpCollector",
    "verify_runtime_notification_webhook_signature",
]
