"""Frozen CSV column order and scalar types for F027 project exports."""

from __future__ import annotations

from typing import Mapping


ColumnSchema = tuple[tuple[str, str], ...]


def _estimate_columns(prefix: str) -> ColumnSchema:
    return tuple(
        (f"{prefix}_{suffix}", value_type)
        for suffix, value_type in (
            ("numerator", "integer"),
            ("denominator", "integer"),
            ("share", "decimal(6)"),
            ("ci_low", "decimal(6)"),
            ("ci_high", "decimal(6)"),
        )
    )


CSV_SCHEMAS: Mapping[str, ColumnSchema] = {
    "protocols.csv": (
        ("schema_version", "string"),
        ("id", "uuid"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("name", "string"),
        ("platform", "string"),
        ("locale", "string"),
        ("device", "string"),
        ("sample_size", "integer"),
        ("window_days", "integer"),
        ("status", "string"),
        ("protocol_hash", "nullable[sha256]"),
        ("source_strata_hash", "nullable[sha256]"),
        ("minimum_valid_repeats", "nullable[integer]"),
        ("statistics_method_version", "nullable[string]"),
        ("statistics_contract_version", "string"),
        ("approved_at", "nullable[timestamp]"),
        ("frozen_at", "nullable[timestamp]"),
    ),
    "protocol_source_strata.csv": (
        ("schema_version", "string"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("protocol_id", "uuid"),
        ("source_stratum_hash", "sha256"),
        ("source_contract_version", "string"),
        ("capture_method", "string"),
        ("platform", "string"),
        ("platform_detail", "nullable[string]"),
        ("surface", "string"),
        ("surface_detail", "nullable[string]"),
        ("surface_kind", "string"),
        ("engine", "string"),
        ("configured_model_state", "string"),
        ("configured_model", "nullable[string]"),
        ("reported_model_state", "string"),
        ("reported_model", "nullable[string]"),
        ("locale", "string"),
        ("region", "string"),
        ("language", "string"),
        ("device", "string"),
        ("client_kind", "string"),
        ("search_enabled", "boolean"),
        ("search_mode", "string"),
    ),
    "queries.csv": (
        ("schema_version", "string"),
        ("id", "uuid"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("protocol_id", "uuid"),
        ("monitoring_query_id", "uuid"),
        ("query_text", "string"),
        ("query_kind", "string"),
        ("locale", "string"),
        ("ordinal", "integer"),
        ("query_cluster_key", "nullable[string]"),
    ),
    "observations.csv": (
        ("schema_version", "string"),
        ("id", "uuid"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("protocol_id", "uuid"),
        ("monitoring_query_id", "uuid"),
        ("query_cluster_key", "nullable[string]"),
        ("measurement_window", "string"),
        ("source_stratum_hash", "nullable[sha256]"),
        ("sample_index", "integer"),
        ("result_status", "string"),
        ("eligible", "boolean"),
        ("url_verification_status", "string"),
        ("recommendation_present", "boolean"),
        ("primary_product_mentioned", "boolean"),
        ("competitor_mentioned", "boolean"),
        ("capture_method", "string"),
        ("platform", "string"),
        ("surface", "string"),
        ("engine", "nullable[string]"),
        ("answer_text", "nullable[string]"),
        ("payload_hash", "sha256"),
        ("observed_at", "timestamp"),
    ),
    "observation_ineligible_reasons.csv": (
        ("schema_version", "string"),
        ("observation_id", "uuid"),
        ("reason", "string"),
    ),
    "observation_confounding_factors.csv": (
        ("schema_version", "string"),
        ("observation_id", "uuid"),
        ("factor", "string"),
    ),
    "citations.csv": (
        ("schema_version", "string"),
        ("observation_id", "uuid"),
        ("citation_index", "integer"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("protocol_id", "uuid"),
        ("url", "string"),
        ("title", "nullable[string]"),
        ("verification_status", "string"),
        ("verified_placement", "boolean"),
        ("destination_id", "nullable[uuid]"),
        ("submission_id", "nullable[uuid]"),
        ("verified_at", "nullable[timestamp]"),
    ),
    "metric_snapshots.csv": (
        ("schema_version", "string"),
        ("id", "uuid"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("protocol_id", "uuid"),
        ("measurement_window", "string"),
        ("source_stratum_hash", "nullable[sha256]"),
        ("statistics_contract_version", "string"),
        ("query_cluster_key", "nullable[string]"),
        ("analysis_stratum_hash", "nullable[sha256]"),
        ("observation_membership_version", "nullable[string]"),
        ("observation_membership_count", "nullable[integer]"),
        ("observation_membership_hash", "nullable[sha256]"),
        ("minimum_valid_repeats", "nullable[integer]"),
        ("expected_sample_count", "integer"),
        ("sampled_sample_count", "nullable[integer]"),
        ("eligible_sample_count", "integer"),
        ("invalid_sample_count", "nullable[integer]"),
        ("missing_sample_count", "nullable[integer]"),
        ("sampling_completion_ratio", "nullable[decimal(6)]"),
        ("valid_completion_ratio", "nullable[decimal(6)]"),
        ("query_count", "nullable[integer]"),
        ("sufficient_query_count", "nullable[integer]"),
        ("recommendation_share", "decimal(6)"),
        ("product_mention_share", "decimal(6)"),
        ("placement_citation_share", "decimal(6)"),
        ("qualified_destination_coverage", "decimal(6)"),
        ("verified_placement_coverage", "decimal(6)"),
        ("competitive_delta", "decimal(6)"),
        ("recommendation_ci_low", "nullable[decimal(6)]"),
        ("recommendation_ci_high", "nullable[decimal(6)]"),
        ("product_mention_ci_low", "nullable[decimal(6)]"),
        ("product_mention_ci_high", "nullable[decimal(6)]"),
        ("placement_citation_ci_low", "nullable[decimal(6)]"),
        ("placement_citation_ci_high", "nullable[decimal(6)]"),
        ("recommendation_query_min", "nullable[decimal(6)]"),
        ("recommendation_query_max", "nullable[decimal(6)]"),
        ("product_mention_query_min", "nullable[decimal(6)]"),
        ("product_mention_query_max", "nullable[decimal(6)]"),
        ("placement_citation_query_min", "nullable[decimal(6)]"),
        ("placement_citation_query_max", "nullable[decimal(6)]"),
        ("worst_query_id", "nullable[uuid]"),
        ("status", "string"),
        ("input_hash", "sha256"),
        ("result_hash", "nullable[sha256]"),
        ("method_version", "string"),
        ("computed_at", "timestamp"),
    ),
    "metric_observation_memberships.csv": (
        ("schema_version", "string"),
        ("snapshot_id", "uuid"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("protocol_id", "uuid"),
        ("observation_id", "uuid"),
        ("ordinal", "integer"),
        ("payload_hash", "sha256"),
    ),
    "metric_invalid_reason_counts.csv": (
        ("schema_version", "string"),
        ("metric_snapshot_id", "uuid"),
        ("reason", "string"),
        ("count", "integer"),
    ),
    "metric_declared_confounding_factors.csv": (
        ("schema_version", "string"),
        ("metric_snapshot_id", "uuid"),
        ("factor", "string"),
    ),
    "metric_confounded_reasons.csv": (
        ("schema_version", "string"),
        ("metric_snapshot_id", "uuid"),
        ("reason", "string"),
    ),
    "metric_destinations.csv": (
        ("schema_version", "string"),
        ("metric_snapshot_id", "uuid"),
        ("destination_set", "string"),
        ("destination_id", "uuid"),
    ),
    "metric_query_results.csv": (
        ("schema_version", "string"),
        ("metric_snapshot_id", "uuid"),
        ("monitoring_query_id", "uuid"),
        ("query_text_snapshot", "string"),
        ("query_cluster_key", "string"),
        ("expected_sample_count", "integer"),
        ("sampled_sample_count", "integer"),
        ("valid_sample_count", "integer"),
        ("invalid_sample_count", "integer"),
        ("missing_sample_count", "integer"),
        ("meets_threshold", "boolean"),
        *_estimate_columns("recommendation"),
        *_estimate_columns("product_mention"),
        *_estimate_columns("placement_citation"),
        *_estimate_columns("competitor"),
        ("competitive_delta", "decimal(6)"),
    ),
    "metric_query_invalid_reason_counts.csv": (
        ("schema_version", "string"),
        ("metric_snapshot_id", "uuid"),
        ("monitoring_query_id", "uuid"),
        ("reason", "string"),
        ("count", "integer"),
    ),
    "metric_query_confounding_factors.csv": (
        ("schema_version", "string"),
        ("metric_snapshot_id", "uuid"),
        ("monitoring_query_id", "uuid"),
        ("factor", "string"),
    ),
    "approved_reports.csv": (
        ("schema_version", "string"),
        ("id", "uuid"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("protocol_id", "uuid"),
        ("metric_snapshot_id", "uuid"),
        ("title", "string"),
        ("body", "string"),
        ("methodology_statement", "string"),
        ("report_hash", "sha256"),
        ("generated_at", "timestamp"),
        ("approved_at", "timestamp"),
    ),
    "verified_urls.csv": (
        ("schema_version", "string"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("url", "string"),
        ("title", "nullable[string]"),
        ("destination_id", "nullable[uuid]"),
        ("first_verified_at", "timestamp"),
        ("observation_count", "integer"),
    ),
    "verified_url_protocols.csv": (
        ("schema_version", "string"),
        ("project_id", "uuid"),
        ("campaign_id", "uuid"),
        ("url", "string"),
        ("protocol_id", "uuid"),
    ),
}
